My Application: SceneSkybox Class Reference
SceneSkybox Class Reference
#include <SceneSkybox.h>
Public Member Functions
SceneSkybox ()
~SceneSkybox ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_TYPE, U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC,
U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_TYPE, U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC,
U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TOTAL
}
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_SPHERE0, GEO_SPHERE1,
GEO_SPHERE2, GEO_SPHERE3, GEO_SPHERE4, GEO_SPHERE5,
GEO_SPHERE6, GEO_SPHERE7, GEO_SPHERE8, GEO_LIGHTBALL,
GEO_LIGHTBALL2, GEO_CYLINDER, GEO_LEFT, GEO_RIGHT,
GEO_TOP, GEO_BOTTOM, GEO_FRONT, GEO_BACK,
NUM_GEOMETRY
}
Private Member Functions
void RenderSkybox ()
void RenderMesh (Mesh *mesh, bool enableLight)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
float worldSize
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
Light lights [2]
Detailed Description
Definition at line 14 of file SceneSkybox.h.
Member Enumeration Documentation
enum SceneSkybox::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_SPHERE0
GEO_SPHERE1
GEO_SPHERE2
GEO_SPHERE3
GEO_SPHERE4
GEO_SPHERE5
GEO_SPHERE6
GEO_SPHERE7
GEO_SPHERE8
GEO_LIGHTBALL
GEO_LIGHTBALL2
GEO_CYLINDER
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
NUM_GEOMETRY
Definition at line 58 of file SceneSkybox.h.
enum SceneSkybox::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_TYPE
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_TYPE
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TOTAL
Definition at line 17 of file SceneSkybox.h.
Constructor & Destructor Documentation
SceneSkybox::SceneSkybox ()
Definition at line 14 of file SceneSkybox.cpp.
SceneSkybox::~SceneSkybox ()
Definition at line 18 of file SceneSkybox.cpp.
Member Function Documentation
void SceneSkybox::Exit () virtual
Implements Scene.
Definition at line 369 of file SceneSkybox.cpp.
References m_programID, m_vertexArrayID, meshList, and NUM_GEOMETRY.
void SceneSkybox::Init () virtual
Implements Scene.
Definition at line 22 of file SceneSkybox.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateQuad(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_QUAD, GEO_RIGHT, GEO_TOP, Camera3::Init(), Light::kC, Light::kL, Light::kQ, Light::LIGHT_POINT, Light::LIGHT_SPOT, lights, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, NUM_GEOMETRY, Light::position, Light::power, projectionStack, rotateAngle, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, and worldSize.
void SceneSkybox::Render () virtual
Implements Scene.
Definition at line 210 of file SceneSkybox.cpp.
References camera, GEO_QUAD, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, lights, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Light::position, Camera::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), MS::Scale(), Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneSkybox::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 323 of file SceneSkybox.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), and RenderSkybox().
void SceneSkybox::RenderSkybox () private
Definition at line 273 of file SceneSkybox.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), and worldSize.
Referenced by Render().
void SceneSkybox::Update (double dt) virtual
Implements Scene.
Definition at line 181 of file SceneSkybox.cpp.
References camera, Application::IsKeyPressed(), rotateAngle, and toggleLight.
Field Documentation
Camera3 SceneSkybox::camera private
Definition at line 103 of file SceneSkybox.h.
Referenced by Init(), Render(), and Update().
Light SceneSkybox::lights[2] private
Definition at line 107 of file SceneSkybox.h.
Referenced by Init(), and Render().
unsigned SceneSkybox::m_parameters[U_TOTAL] private
Definition at line 97 of file SceneSkybox.h.
Referenced by Init(), Render(), and RenderMesh().
unsigned SceneSkybox::m_programID private
Definition at line 96 of file SceneSkybox.h.
Referenced by Exit(), and Init().
unsigned SceneSkybox::m_vertexArrayID private
Definition at line 94 of file SceneSkybox.h.
Referenced by Exit(), and Init().
Mesh* SceneSkybox::meshList[NUM_GEOMETRY] private
Definition at line 95 of file SceneSkybox.h.
Referenced by Exit(), Init(), Render(), and RenderSkybox().
MS SceneSkybox::modelStack private
Definition at line 105 of file SceneSkybox.h.
Referenced by Render(), RenderMesh(), and RenderSkybox().
MS SceneSkybox::projectionStack private
Definition at line 105 of file SceneSkybox.h.
Referenced by Init(), and RenderMesh().
float SceneSkybox::rotateAngle private
Definition at line 99 of file SceneSkybox.h.
Referenced by Init(), and Update().
MS SceneSkybox::viewStack private
Definition at line 105 of file SceneSkybox.h.
Referenced by Render(), and RenderMesh().
float SceneSkybox::worldSize private
Definition at line 100 of file SceneSkybox.h.
Referenced by Init(), and RenderSkybox().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneSkybox.h
MyGraphics/Source/SceneSkybox.cpp