My Application: sf::SoundStream Class Reference
sf::SoundStream Class Reference abstract
Audio module
Abstract base class for streamed audio sources.
#include <SoundStream.hpp>
Data Structures
struct Chunk
Structure defining a chunk of audio data to stream.
Public Member Functions
virtual ~SoundStream ()
Destructor.
void play ()
Start or resume playing the audio stream.
void pause ()
Pause the audio stream.
void stop ()
Stop playing the audio stream.
unsigned int getChannelCount () const
Return the number of channels of the stream.
unsigned int getSampleRate () const
Get the stream sample rate of the stream.
Status getStatus () const
Get the current status of the stream (stopped, paused, playing)
void setPlayingOffset (Time timeOffset)
Change the current playing position of the stream.
Time getPlayingOffset () const
Get the current playing position of the stream.
void setLoop (bool loop)
Set whether or not the stream should loop after reaching the end.
bool getLoop () const
Tell whether or not the stream is in loop mode.
Public Member Functions inherited from sf::SoundSource
SoundSource (const SoundSource &copy)
Copy constructor.
virtual ~SoundSource ()
Destructor.
void setPitch (float pitch)
Set the pitch of the sound.
void setVolume (float volume)
Set the volume of the sound.
void setPosition (float x, float y, float z)
Set the 3D position of the sound in the audio scene.
void setPosition (const Vector3f &position)
Set the 3D position of the sound in the audio scene.
void setRelativeToListener (bool relative)
Make the sound's position relative to the listener or absolute.
void setMinDistance (float distance)
Set the minimum distance of the sound.
void setAttenuation (float attenuation)
Set the attenuation factor of the sound.
float getPitch () const
Get the pitch of the sound.
float getVolume () const
Get the volume of the sound.
Vector3f getPosition () const
Get the 3D position of the sound in the audio scene.
bool isRelativeToListener () const
Tell whether the sound's position is relative to the listener or is absolute.
float getMinDistance () const
Get the minimum distance of the sound.
float getAttenuation () const
Get the attenuation factor of the sound.
Protected Member Functions
SoundStream ()
Default constructor.
void initialize (unsigned int channelCount, unsigned int sampleRate)
Define the audio stream parameters.
virtual bool onGetData (Chunk &data)=0
Request a new chunk of audio samples from the stream source.
virtual void onSeek (Time timeOffset)=0
Change the current playing position in the stream source.
Protected Member Functions inherited from sf::SoundSource
SoundSource ()
Default constructor.
Status getStatus () const
Get the current status of the sound (stopped, paused, playing)
Private Types
enum { BufferCount = 3 }
Private Member Functions
void streamData ()
Function called as the entry point of the thread.
bool fillAndPushBuffer (unsigned int bufferNum)
Fill a new buffer with audio samples, and append it to the playing queue.
bool fillQueue ()
Fill the audio buffers and put them all into the playing queue.
void clearQueue ()
Clear all the audio buffers and empty the playing queue.
Private Attributes
Thread m_thread
Thread running the background tasks.
Mutex m_threadMutex
Thread mutex.
Status m_threadStartState
State the thread starts in (Playing, Paused, Stopped)
bool m_isStreaming
Streaming state (true = playing, false = stopped)
unsigned int m_buffers [BufferCount]
Sound buffers used to store temporary audio data.
unsigned int m_channelCount
Number of channels (1 = mono, 2 = stereo, ...)
unsigned int m_sampleRate
Frequency (samples / second)
Uint32 m_format
Format of the internal sound buffers.
bool m_loop
Loop flag (true to loop, false to play once)
Uint64 m_samplesProcessed
Number of buffers processed since beginning of the stream.
bool m_endBuffers [BufferCount]
Each buffer is marked as "end buffer" or not, for proper duration calculation.
Additional Inherited Members
Public Types inherited from sf::SoundSource
enum Status { Stopped, Paused, Playing }
Enumeration of the sound source states.
Protected Attributes inherited from sf::SoundSource
unsigned int m_source
OpenAL source identifier.
Detailed Description
Abstract base class for streamed audio sources.
Unlike audio buffers (see sf::SoundBuffer), audio streams are never completely loaded in memory.
Instead, the audio data is acquired continuously while the stream is playing. This behavior allows to play a sound with no loading delay, and keeps the memory consumption very low.
Sound sources that need to be streamed are usually big files (compressed audio musics that would eat hundreds of MB in memory) or files that would take a lot of time to be received (sounds played over the network).
sf::SoundStream is a base class that doesn't care about the stream source, which is left to the derived class. SFML provides a built-in specialization for big files (see sf::Music). No network stream source is provided, but you can write your own by combining this class with the network module.
A derived class has to override two virtual functions:
onGetData fills a new chunk of audio data to be played
onSeek changes the current playing position in the source
It is important to note that each SoundStream is played in its own separate thread, so that the streaming loop doesn't block the rest of the program. In particular, the OnGetData and OnSeek virtual functions may sometimes be called from this separate thread. It is important to keep this in mind, because you may have to take care of synchronization issues if you share data between threads.
Usage example:
class CustomStream : public sf::SoundStream
{
public:
    bool open(const std::string& location)
    {
        // Open the source and get audio settings
        ...
        unsigned int channelCount = ...;
        unsigned int sampleRate = ...;
        // Initialize the stream -- important!
        initialize(channelCount, sampleRate);
    }
private:
    virtual bool onGetData(Chunk& data)
    {
        // Fill the chunk with audio data from the stream source
        // (note: must not be empty if you want to continue playing)
        data.samples = ...;
        data.sampleCount = ...;
        // Return true to continue playing
        return true;
    }
    virtual void onSeek(Uint32 timeOffset)
    {
        // Change the current position in the stream source
        ...
    }
}
// Usage
CustomStream stream;
stream.open("path/to/stream");
stream.play();
See also
sf::Music
Definition at line 45 of file SoundStream.hpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
BufferCount
Number of audio buffers used by the streaming loop.
Definition at line 282 of file SoundStream.hpp.
Constructor & Destructor Documentation
virtual sf::SoundStream::~SoundStream () virtual
Destructor.
sf::SoundStream::SoundStream () protected
Default constructor.
This constructor is only meant to be called by derived classes.
Member Function Documentation
void sf::SoundStream::clearQueue () private
Clear all the audio buffers and empty the playing queue.
This function is called when the stream is stopped.
bool sf::SoundStream::fillAndPushBuffer (unsigned int bufferNum) private
Fill a new buffer with audio samples, and append it to the playing queue.
This function is called as soon as a buffer has been fully consumed; it fills it again and inserts it back into the playing queue.
Parameters
bufferNum Number of the buffer to fill (in [0, BufferCount])
Returns
True if the stream source has requested to stop, false otherwise
bool sf::SoundStream::fillQueue () private
Fill the audio buffers and put them all into the playing queue.
This function is called when playing starts and the playing queue is empty.
Returns
True if the derived class has requested to stop, false otherwise
unsigned int sf::SoundStream::getChannelCount () const
Return the number of channels of the stream.
1 channel means a mono sound, 2 means stereo, etc.
Returns
Number of channels
bool sf::SoundStream::getLoop () const
Tell whether or not the stream is in loop mode.
Returns
True if the stream is looping, false otherwise
See also
setLoop
Time sf::SoundStream::getPlayingOffset () const
Get the current playing position of the stream.
Returns
Current playing position, from the beginning of the stream
See also
setPlayingOffset
unsigned int sf::SoundStream::getSampleRate () const
Get the stream sample rate of the stream.
The sample rate is the number of audio samples played per second. The higher, the better the quality.
Returns
Sample rate, in number of samples per second
Status sf::SoundStream::getStatus () const
Get the current status of the stream (stopped, paused, playing)
Returns
Current status
Referenced by SceneSP::UpdatePlaying().
void sf::SoundStream::initialize (unsigned int channelCount, unsigned int sampleRate) protected
Define the audio stream parameters.
This function must be called by derived classes as soon as they know the audio settings of the stream to play. Any attempt to manipulate the stream (play(), ...) before calling this function will fail. It can be called multiple times if the settings of the audio stream change, but only when the stream is stopped.
Parameters
channelCount Number of channels of the stream
sampleRate Sample rate, in samples per second
virtual bool sf::SoundStream::onGetData (Chunk & data) protected pure virtual
Request a new chunk of audio samples from the stream source.
This function must be overridden by derived classes to provide the audio samples to play. It is called continuously by the streaming loop, in a separate thread. The source can choose to stop the streaming loop at any time, by returning false to the caller. If you return true (i.e. continue streaming) it is important that the returned array of samples is not empty; this would stop the stream due to an internal limitation.
Parameters
data Chunk of data to fill
Returns
True to continue playback, false to stop
Implemented in sf::Music.
virtual void sf::SoundStream::onSeek (Time timeOffset) protected pure virtual
Change the current playing position in the stream source.
This function must be overridden by derived classes to allow random seeking into the stream source.
Parameters
timeOffset New playing position, relative to the beginning of the stream
Implemented in sf::Music.
void sf::SoundStream::pause ()
Pause the audio stream.
This function pauses the stream if it was playing, otherwise (stream already paused or stopped) it has no effect.
See also
play, stop
void sf::SoundStream::play ()
Start or resume playing the audio stream.
This function starts the stream if it was stopped, resumes it if it was paused, and restarts it from the beginning if it was already playing. This function uses its own thread so that it doesn't block the rest of the program while the stream is played.
See also
pause, stop
Referenced by SceneSP::Init(), SceneSP::UpdateCage(), SceneSP::UpdateDoor(), SceneSP::UpdateElevator(), SceneSP::UpdateGaben(), SceneSP::UpdateMiscEasteregg(), SceneSP::UpdatePlaying(), SceneSP::UpdateSamples(), and SceneSP::UpdateTroll().
void sf::SoundStream::setLoop (bool loop)
Set whether or not the stream should loop after reaching the end.
If set, the stream will restart from beginning after reaching the end and so on, until it is stopped or setLoop(false) is called. The default looping state for streams is false.
Parameters
loop True to play in loop, false to play once
See also
getLoop
Referenced by SceneSP::Init(), SceneSP::UpdateCage(), SceneSP::UpdateDoor(), SceneSP::UpdateElevator(), SceneSP::UpdateGaben(), SceneSP::UpdateMiscEasteregg(), SceneSP::UpdatePlaying(), SceneSP::UpdateSamples(), and SceneSP::UpdateTroll().
void sf::SoundStream::setPlayingOffset (Time timeOffset)
Change the current playing position of the stream.
The playing position can be changed when the stream is either paused or playing. Changing the playing position when the stream is stopped has no effect, since playing the stream would reset its position.
Parameters
timeOffset New playing position, from the beginning of the stream
See also
getPlayingOffset
void sf::SoundStream::stop ()
Stop playing the audio stream.
This function stops the stream if it was playing or paused, and does nothing if it was already stopped. It also resets the playing position (unlike pause()).
See also
play, pause
Referenced by SceneSP::Exit(), and SceneSP::UpdateStartMenu().
void sf::SoundStream::streamData () private
Function called as the entry point of the thread.
This function starts the streaming loop, and returns only when the sound is stopped.
Field Documentation
unsigned int sf::SoundStream::m_buffers[BufferCount] private
Sound buffers used to store temporary audio data.
Definition at line 294 of file SoundStream.hpp.
unsigned int sf::SoundStream::m_channelCount private
Number of channels (1 = mono, 2 = stereo, ...)
Definition at line 295 of file SoundStream.hpp.
bool sf::SoundStream::m_endBuffers[BufferCount] private
Each buffer is marked as "end buffer" or not, for proper duration calculation.
Definition at line 300 of file SoundStream.hpp.
Uint32 sf::SoundStream::m_format private
Format of the internal sound buffers.
Definition at line 297 of file SoundStream.hpp.
bool sf::SoundStream::m_isStreaming private
Streaming state (true = playing, false = stopped)
Definition at line 293 of file SoundStream.hpp.
bool sf::SoundStream::m_loop private
Loop flag (true to loop, false to play once)
Definition at line 298 of file SoundStream.hpp.
unsigned int sf::SoundStream::m_sampleRate private
Frequency (samples / second)
Definition at line 296 of file SoundStream.hpp.
Uint64 sf::SoundStream::m_samplesProcessed private
Number of buffers processed since beginning of the stream.
Definition at line 299 of file SoundStream.hpp.
Thread sf::SoundStream::m_thread private
Thread running the background tasks.
Definition at line 290 of file SoundStream.hpp.
Mutex sf::SoundStream::m_threadMutex mutable private
Thread mutex.
Definition at line 291 of file SoundStream.hpp.
Status sf::SoundStream::m_threadStartState private
State the thread starts in (Playing, Paused, Stopped)
Definition at line 292 of file SoundStream.hpp.
The documentation for this class was generated from the following file:
SFML/include/SFML/Audio/SoundStream.hpp