My Application: CBranCan Class Reference
CBranCan Class Reference
Defines BranCan class.
#include <BranCan.h>
Public Member Functions
CBranCan (void)
Default constructor.
~CBranCan (void)
Default destructor.
Public Member Functions inherited from CItem
CItem (void)
Default item constructor.
CItem (string n, float p, int type, float posX, float posY, float posZ)
Overloaded item constructor.
void setName (string n)
Mutator function to set the item name.
void setPrice (float p)
Mutator function to set the item price.
void setGeoType (int type)
Mutator function to set the item geometry type.
void setXpos (float posX)
Mutator function to set the x position of the item.
void setYpos (float posY)
Mutator function to set the y position of the item.
void setZpos (float posZ)
Mutator function to set the z position of the item.
void setActiveState (bool setActive)
Mutator function to set the active state of the item.
bool getActiveState ()
Accessor function for item active state.
float getXpos ()
Accessor function for item x position.
float getYpos ()
Accessor function for item y position.
float getZpos ()
Accessor function for item Zposition.
string getName ()
Accessor function for item name.
int getGeoType ()
Accessor function for item geometry type.
float getPrice ()
Accessor function for item price.
~CItem (void)
Default destructor.
Detailed Description
Defines BranCan class.
Class BranCan:
Definition at line 10 of file BranCan.h.
Constructor & Destructor Documentation
CBranCan::CBranCan (void)
Default constructor.
Definition at line 9 of file BranCan.cpp.
References GEO_CAN_BRAN, CItem::setGeoType(), CItem::setName(), and CItem::setPrice().
CBranCan::~CBranCan (void)
Default destructor.
Definition at line 22 of file BranCan.cpp.
The documentation for this class was generated from the following files:
MyGraphics/Source/BranCan.h
MyGraphics/Source/BranCan.cpp