My Application: CItem Class Reference
CItem Class Reference
Defines item class.
#include <Item.h>
Public Member Functions
CItem (void)
Default item constructor.
CItem (string n, float p, int type, float posX, float posY, float posZ)
Overloaded item constructor.
void setName (string n)
Mutator function to set the item name.
void setPrice (float p)
Mutator function to set the item price.
void setGeoType (int type)
Mutator function to set the item geometry type.
void setXpos (float posX)
Mutator function to set the x position of the item.
void setYpos (float posY)
Mutator function to set the y position of the item.
void setZpos (float posZ)
Mutator function to set the z position of the item.
void setActiveState (bool setActive)
Mutator function to set the active state of the item.
bool getActiveState ()
Accessor function for item active state.
float getXpos ()
Accessor function for item x position.
float getYpos ()
Accessor function for item y position.
float getZpos ()
Accessor function for item Zposition.
string getName ()
Accessor function for item name.
int getGeoType ()
Accessor function for item geometry type.
float getPrice ()
Accessor function for item price.
~CItem (void)
Default destructor.
Private Attributes
string name
float price
int objectType
float x
float y
float z
bool active
Detailed Description
Defines item class.
Class Item:
Definition at line 13 of file Item.h.
Constructor & Destructor Documentation
CItem::CItem (void)
Default item constructor.
Definition at line 8 of file Item.cpp.
References name, objectType, and price.
CItem::CItem (string n, float p, int type, float posX, float posY, float posZ)
Overloaded item constructor.
Parameters
n - name of item
p - price of item
type - type of item
posX - x position of item
posY - y position of item
posZ - z position of item
Definition at line 27 of file Item.cpp.
References name, objectType, price, x, y, and z.
CItem::~CItem (void)
Default destructor.
Definition at line 43 of file Item.cpp.
Member Function Documentation
bool CItem::getActiveState ()
Accessor function for item active state.
Returns
item active state
Definition at line 138 of file Item.cpp.
References active.
int CItem::getGeoType ()
Accessor function for item geometry type.
Returns
item geometry type
Definition at line 150 of file Item.cpp.
References objectType.
Referenced by SceneSP::DefineItem(), and SceneSP::RenderHand().
string CItem::getName ()
Accessor function for item name.
Returns
item name
Definition at line 198 of file Item.cpp.
References name.
Referenced by SceneSP::addToInventory(), SceneSP::checkPickUpItem(), SceneSP::checkReturnPoint(), SceneSP::checkWinLose(), SceneSP::DefineItem(), SceneSP::RenderHand(), SceneSP::RenderUI(), and SceneSP::UpdatePlayerSelection().
float CItem::getPrice ()
Accessor function for item price.
Returns
item price
Definition at line 210 of file Item.cpp.
References price.
Referenced by SceneSP::DefineItem(), and SceneSP::UpdateUI().
float CItem::getXpos ()
Accessor function for item x position.
Returns
item X position
Definition at line 162 of file Item.cpp.
References x.
float CItem::getYpos ()
Accessor function for item y position.
Returns
item Yposition
Definition at line 174 of file Item.cpp.
References y.
float CItem::getZpos ()
Accessor function for item Zposition.
Returns
item Z position
Definition at line 186 of file Item.cpp.
References z.
void CItem::setActiveState (bool setActive)
Mutator function to set the active state of the item.
Parameters
setActive - set active state of item
Definition at line 90 of file Item.cpp.
References active.
void CItem::setGeoType (int type)
Mutator function to set the item geometry type.
Parameters
type - set item geometry type
Definition at line 78 of file Item.cpp.
References objectType.
Referenced by CBeansCan::CBeansCan(), CBranCan::CBranCan(), CBrownCan::CBrownCan(), CCerealBox1::CCerealBox1(), CCerealBox2::CCerealBox2(), CCerealBox3::CCerealBox3(), CCerealBox4::CCerealBox4(), CCerealBox5::CCerealBox5(), CEasterEgg1::CEasterEgg1(), CEasterEgg2::CEasterEgg2(), CEasterEgg3::CEasterEgg3(), CEmptyItem::CEmptyItem(), CGluWaterCan::CGluWaterCan(), CHumanCan::CHumanCan(), CMelonCan::CMelonCan(), CMtnDewCan::CMtnDewCan(), CPeasCan::CPeasCan(), CRedMonsterCan::CRedMonsterCan(), CRootBeerFloatsCan::CRootBeerFloatsCan(), CSardineCan::CSardineCan(), CSodaCan::CSodaCan(), CSodaFestCan::CSodaFestCan(), CTomatoCan::CTomatoCan(), CVargaCan::CVargaCan(), CWinebottle1::CWinebottle1(), CWinebottle2::CWinebottle2(), CWinebottle3::CWinebottle3(), CWinebottle4::CWinebottle4(), and CWinebottle5::CWinebottle5().
void CItem::setName (string n)
Mutator function to set the item name.
Parameters
n - set item name
Definition at line 54 of file Item.cpp.
References name.
Referenced by CBeansCan::CBeansCan(), CBranCan::CBranCan(), CBrownCan::CBrownCan(), CCerealBox1::CCerealBox1(), CCerealBox2::CCerealBox2(), CCerealBox3::CCerealBox3(), CCerealBox4::CCerealBox4(), CCerealBox5::CCerealBox5(), CEasterEgg1::CEasterEgg1(), CEasterEgg2::CEasterEgg2(), CEasterEgg3::CEasterEgg3(), CEmptyItem::CEmptyItem(), CGluWaterCan::CGluWaterCan(), CHumanCan::CHumanCan(), CMelonCan::CMelonCan(), CMtnDewCan::CMtnDewCan(), CPeasCan::CPeasCan(), CRedMonsterCan::CRedMonsterCan(), CRootBeerFloatsCan::CRootBeerFloatsCan(), CSardineCan::CSardineCan(), CSodaCan::CSodaCan(), CSodaFestCan::CSodaFestCan(), CTomatoCan::CTomatoCan(), CVargaCan::CVargaCan(), CWinebottle1::CWinebottle1(), CWinebottle2::CWinebottle2(), CWinebottle3::CWinebottle3(), CWinebottle4::CWinebottle4(), and CWinebottle5::CWinebottle5().
void CItem::setPrice (float p)
Mutator function to set the item price.
Parameters
n - set item price
Definition at line 66 of file Item.cpp.
References price.
Referenced by CBeansCan::CBeansCan(), CBranCan::CBranCan(), CBrownCan::CBrownCan(), CCerealBox1::CCerealBox1(), CCerealBox2::CCerealBox2(), CCerealBox3::CCerealBox3(), CCerealBox4::CCerealBox4(), CCerealBox5::CCerealBox5(), CEasterEgg1::CEasterEgg1(), CEasterEgg2::CEasterEgg2(), CEasterEgg3::CEasterEgg3(), CEmptyItem::CEmptyItem(), CGluWaterCan::CGluWaterCan(), CHumanCan::CHumanCan(), CMelonCan::CMelonCan(), CMtnDewCan::CMtnDewCan(), CPeasCan::CPeasCan(), CRedMonsterCan::CRedMonsterCan(), CRootBeerFloatsCan::CRootBeerFloatsCan(), CSardineCan::CSardineCan(), CSodaCan::CSodaCan(), CSodaFestCan::CSodaFestCan(), CTomatoCan::CTomatoCan(), CVargaCan::CVargaCan(), CWinebottle1::CWinebottle1(), CWinebottle2::CWinebottle2(), CWinebottle3::CWinebottle3(), CWinebottle4::CWinebottle4(), and CWinebottle5::CWinebottle5().
void CItem::setXpos (float posX)
Mutator function to set the x position of the item.
Parameters
posX - set item X position
Definition at line 102 of file Item.cpp.
References x.
void CItem::setYpos (float posY)
Mutator function to set the y position of the item.
Parameters
posX - set item Y position
Definition at line 114 of file Item.cpp.
References y.
void CItem::setZpos (float posZ)
Mutator function to set the z position of the item.
Parameters
posX - set item Z position
Definition at line 126 of file Item.cpp.
References z.
Field Documentation
bool CItem::active private
Definition at line 41 of file Item.h.
Referenced by getActiveState(), and setActiveState().
string CItem::name private
Definition at line 35 of file Item.h.
Referenced by CItem(), getName(), and setName().
int CItem::objectType private
Definition at line 37 of file Item.h.
Referenced by CItem(), getGeoType(), and setGeoType().
float CItem::price private
Definition at line 36 of file Item.h.
Referenced by CItem(), getPrice(), and setPrice().
float CItem::x private
Definition at line 38 of file Item.h.
Referenced by CItem(), getXpos(), and setXpos().
float CItem::y private
Definition at line 39 of file Item.h.
Referenced by CItem(), getYpos(), and setYpos().
float CItem::z private
Definition at line 40 of file Item.h.
Referenced by CItem(), getZpos(), and setZpos().
The documentation for this class was generated from the following files:
MyGraphics/Source/Item.h
MyGraphics/Source/Item.cpp