My Application: SceneSP Class Reference
SceneSP Class Reference
Defines the class for our entire scene.
#include <SceneSP.h>
Data Structures
struct Transformations
Public Member Functions
SceneSP ()
Default scene constructor.
~SceneSP ()
Default scene destructor.
virtual void Init ()
Initialises the entire scene.
virtual void Update (double dt)
Updates the entire scene.
virtual void Render ()
Renders the entire scene.
virtual void Exit ()
Exits the scene.
void RenderSkyBox ()
Renders the sky box of the scene.
void RenderMesh (Mesh *mesh, bool enableLight)
Renders a mesh.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
double timer
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
Light lights [2]
Transformations Cashier
Private Member Functions
void checkPickUpItem ()
Checks for the picking up of items.
void checkCollision ()
Checks for the collision of all objects in the scene.
void checkObjectCollision (float posX, float posY, float posZ, float widthX, float widthZ)
Checks for the collision of an object.
void checkSupermarketCollision ()
Checks for the collision of the supermarket.
void checkElevatorCollision ()
Checks for the collision of the elevator.
bool checkReturnPoint ()
Checks for players position to return items to the return point.
void checkWinLose ()
Checks for the winning and losing conditions of the current gamemode.
void resetGame ()
Resets the entire game.
void addToInventory (CItem *pickedUp)
Adds items picked up by the player to their inventory.
void RenderText (Mesh *mesh, std::string text, Color color)
Renders text in world space on a mesh.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text on screen.
void RenderTGAUI (Mesh *mesh, float size, float x, float y)
Function to render the targa UI of the player.
void RenderTGAInventory (Mesh *mesh, float size, float x, float y)
Function to render the targa inventory of the player.
void RenderSupermarket ()
Renders the entire supermarket.
void RenderShelves ()
Function to render the shelves in the supermarket.
void RenderShelves (CContainer *container)
Overloaded function which takes in a container to render shelves.
void RenderDoors ()
Renders the front and back doors of the supermarket.
void RenderTrolleys ()
Renders the trolleys in the scene.
void RenderSamplestand ()
Renders the sample stand.
void RenderSamples ()
Renders the samples remaining on the sample stand.
void RenderUI ()
Renders the player's UI.
void RenderTugofwarUI ()
Renders the UI displayed while in the tug of war activity.
void RenderDrunkmanUI ()
Renders the UI displayed when interacting with the drunk man Npc.
void RenderItem ()
Renders the purchasable items in the supermarket.
void RenderCashierTables ()
Renders the cashier tables in the scene.
void RenderInventory ()
Renders the player's inventory.
void RenderFence ()
Renders the fences in the scene.
void RenderElevator ()
Renders the elevator in the scene.
void RenderCharacters ()
Renders all Npcs.
void RenderCharacter (CNpc *npc)
Function to render the targa inventory of the player.
void RenderHand ()
Renders the player's hand.
void RenderTug ()
Renders the tug of war activity.
void RenderReturnPoint ()
Renders the item return point.
void RenderBeerstand ()
Renders the beer stands.
void RenderMainMenu ()
Renders the main menu.
void RenderSubMenu ()
Renders the sub menu displaying the different gamemodes.
void RenderWinLoseMenu ()
Renders the win / lose menu.
void RenderInstructionMenu ()
Renders the instruction menu.
void RenderPauseMenu ()
Renders the pause menu.
void RenderOffice ()
Renders the logistics staff office.
void RenderStorage ()
Renders the storage room.
void RenderBuilding ()
Renders the buildings outside the supermarket.
void RenderIceBox ()
Renders the ice boxes.
void RenderMeatShelf ()
Renders the meat shelves.
void RenderFoodShelf ()
void RenderCage ()
Renders the "cage" easter egg.
void RenderTroll ()
Renders the "troll" easter egg.
void RenderMiscEastereggs ()
Renders miscellaneous easter eggs.
void RenderEasteregg ()
Renders all easter eggs if in easter egg gamemode.
void RenderATM ()
Renders the ATM.
void RenderFerrisWheel ()
Renders the ferris wheel.
void UpdateAI (double dt)
Updates the movement of all Npcs in the scene based on dt.
void UpdateHand (double dt)
Updates the player's hand movement based on dt.
void UpdateDoor (double dt)
Updates the opening and closing of the front and back doors based on dt.
void UpdateUI (double dt)
Updates the players UI.
void UpdateSamples ()
Updates the remaining samples on the sample stand.
void UpdateElevator (double dt)
Updates the movement of the elevator based on dt.
void UpdateMenu ()
Updates the switching between menus.
void UpdateMainMenu ()
Updates the main menu upon starting up.
void UpdateStartMenu ()
Updates the Start menu.
void UpdateWinLoseMenu ()
Updates the win / lose menu.
void UpdateInstructionMenu ()
Updates the instruction menu.
void UpdatePauseMenu ()
Updates the pause menu.
void UpdatePlaying (double dt)
Updates the scene when the player is ingame.
void UpdateTugofwar (double dt)
Updates the player during the tug of war activity based on dt.
void UpdateDrunkman (double dt)
Updates the picking up of the Drunkman Npc based on dt.
void UpdatePlayerSelection ()
Updates the selection of inventory slot by the player.
void UpdateItemRotation (double dt)
Updates the item rotation based on dt.
void UpdateTugofwarguy (double dt)
Updates the Npc involves in the tug of war activity based on dt.
void UpdateDrunkmanguy (double dt)
Updates the movement of the Drunkman Npc based on dt.
void UpdateWalkingman (double dt)
Updates the movement of the Npcs walking inside the supermarket based on dt.
void UpdateWalkingmanoutsideX (double dt)
Updates the movement of the Passer-by Npcs outside the supermarket moving in the X direction based on dt.
void UpdateWalkingmanoutsideZ (double dt)
Updates the movement of the Passer-by Npcs outside the supermarket moving in the Z direction based on dt.
void UpdateLogisticman (double dt)
Updates the movement of the logistics Npc based on dt.
void UpdateGhostman (double dt)
Updates the movement of the Ghost Npc based on dt.
void UpdateCustomer (double dt)
Updates the movement of the customers based on dt.
void UpdateShoppers (double dt)
Updates the movement of the shoppers based on dt.
void UpdateLookingman (double dt)
Updates the movement of the Npc looking at items based on dt.
void UpdateChattingman (double dt)
Updates the movement of the chatting Npc based on dt.
void UpdateLegAnimation (double dt)
Updates the leg animation of all Npcs while they are moving based on dt.
void UpdateItemInspection ()
Updates the inspection of items.
void UpdateAITimer (double dt)
Updates the Npcs interaction timers based on dt.
void UpdatePaying ()
Updates the paying of money.
void UpdateCage (double dt)
Updates the "cage" easter egg based on dt.
void UpdateGaben (double dt)
Updates the "gabe" easter egg based on dt.
void UpdateTroll (double dt)
Updates the "troll" easter egg based on dt.
void UpdateMiscEasteregg (double dt)
Updates the miscellaneous easter eggs based on dt.
void UpdateEasteregg (double dt)
Updates all easter eggs in the easter egg gamemode.
void UpdateEasterEggGuy (double dt)
Updates the movement of EasterEggGuy Npc based on dt.
void UpdateATM ()
Updates the addition of the player's money and deduction of the ATM's money.
void UpdateBuildingGuy (double dt)
Updates the movement of BuildingGuy Npc based on dt.
void DeclareLightParameters ()
Declares all light parameters.
void DeclareGLEnable ()
Declares GLEnable.
void DefineItem (CContainer *container, CItem item, int row)
Defines all items and containers.
void initGeoType ()
Initialises all geometry types.
void initCharacter ()
Initialises the player and all NPCs.
void initNPC ()
void initShelves ()
Initialises all shelves in the scene.
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
CContainer shelfSardineCan
bool toggleLight
bool toggleDoorFront
bool toggleDoorBack
bool elevatorDoorOpening
bool elevatorSecondFloor
bool b_isWithinInteractionItem
bool b_isWithinPayingCashier
bool b_is_Stealing
bool b_dinged
bool falling
float interactionTimer
float LogisticinteractionTimer
float CustomerinteractionTimer
float moveDoorFront
float moveDoorBack
float trolleyrotation
float handrotationleftandright
float handtranslation
float diffX
float diffZ
float charactersrotation
float elevatorDoorY
float elevatorY
float itemYrotation
float itemXrotation
float ATMMoney
float f_soundTimer
CEmptyItem emptyItem
float easterLimiter
float easterLimiter2
float easterTimer
float cagedPos
float diffY
int getCounter
bool winEaster
bool closeEaster
bool inRange
bool getCaged
bool getGabed
bool getTrolled
bool getTimed
bool getRicked
bool caged
bool win
bool lose
bool showTuginstruction
bool b_crouching
bool b_inspection
int i_total_items_to_find
int i_sampleItems
int i_menuHandle
int i_drunkmanAct
int i_CashierAct
bool elevatorIdle
bool IsIntugofwar
string s_money
string s_position
string s_fps
string s_camera_target
string s_item_name
string s_item_price
string s_easter_counter
string s_easter_count
string s_atm_balance
CPlayer * ptrplayer
CItem * ptrItem
CItem * ptrClass
CItem * ptrInvSelect
CNpc * ptrNPC
int selectionPointing
int inventoryPointing
CContainer * ptrContainer
vector< CContainer * > myContainerList
vector< CItem * > myStockList
vector< CItem * > myTreasureList
vector< CItem * > myCheckList
vector< CNpc * > myNPCList
sf::Music music
sf::Music music2
sf::Music sound
sf::Music easter
Detailed Description
Defines the class for our entire scene.
Class SceneSP:
Definition at line 32 of file SceneSP.h.
Constructor & Destructor Documentation
SceneSP::SceneSP ()
Default scene constructor.
Definition at line 18 of file SceneSP.cpp.
SceneSP::~SceneSP ()
Default scene destructor.
Definition at line 27 of file SceneSP.cpp.
Member Function Documentation
void SceneSP::addToInventory (CItem * pickedUp) private
Adds items picked up by the player to their inventory.
Parameters
pickedUp - item picked up by player
Definition at line 792 of file SceneSP.cpp.
References CItem::getName(), interactionTimer, inventoryPointing, ptrplayer, and CPlayer::setInventory().
Referenced by checkPickUpItem().
void SceneSP::checkCollision () private
Checks for the collision of all objects in the scene.
Definition at line 4880 of file SceneSP.cpp.
References checkElevatorCollision(), checkObjectCollision(), checkSupermarketCollision(), myContainerList, myNPCList, ShelfWidthX, and ShelfWidthZ.
Referenced by UpdatePlaying().
void SceneSP::checkElevatorCollision () private
Checks for the collision of the elevator.
Definition at line 5157 of file SceneSP.cpp.
References camera, diffX, diffZ, EboundX1, EboundX2, EboundX3, EboundZ1, EboundZ2, EboundZ3, elevatorDoorOpening, Camera::position, RenderElevatorPosX, RenderElevatorPosZ, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by checkCollision().
void SceneSP::checkObjectCollision (float posX, float posY, float posZ, float widthX, float widthZ) private
Checks for the collision of an object.
Definition at line 4934 of file SceneSP.cpp.
References camera, Coffset, diffX, diffZ, Camera::position, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by checkCollision().
void SceneSP::checkPickUpItem () private
Checks for the picking up of items.
Definition at line 4818 of file SceneSP.cpp.
References addToInventory(), b_isWithinInteractionItem, camera, emptyItem, CPlayer::getItem(), CItem::getName(), interactionDistance, interactionTimer, interactionTimerLimiter, inventoryPointing, Application::IsKeyPressed(), itemXoffset, itemYoffset, itemZoffset, myStockList, Camera::position, ptrInvSelect, ptrplayer, s_item_name, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
bool SceneSP::checkReturnPoint () private
Checks for players position to return items to the return point.
Definition at line 5210 of file SceneSP.cpp.
References camera, emptyItem, CPlayer::getItem(), CItem::getName(), interactionTimer, interactionTimerLimiter, inventoryPointing, Application::IsKeyPressed(), Camera::position, ptrInvSelect, ptrplayer, returnPointBoxInteractionHeight, returnPointBoxInteractionLength, returnPointBoxInteractionWidth, returnPointBoxPosX, returnPointBoxPosY, returnPointBoxPosZ, returnPointBoxWidthOffset, CPlayer::setInventory(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by RenderUI(), and UpdatePlaying().
void SceneSP::checkSupermarketCollision () private
Checks for the collision of the supermarket.
Definition at line 4978 of file SceneSP.cpp.
References boundX1, boundX10, boundX2, boundX3, boundX4, boundX5, boundX6, boundX7, boundX8, boundX9, boundZ1, boundZ2, boundZ3, boundZ4, boundZ5, boundZ6, camera, diffX, diffZ, Camera::position, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by checkCollision().
void SceneSP::checkWinLose () private
Checks for the winning and losing conditions of the current gamemode.
Definition at line 5253 of file SceneSP.cpp.
References b_is_Stealing, camera, clearText, closeEaster, getCaged, CCharacter::getCharacterJob(), getCounter, getGabed, CItem::getName(), getTimed, getTrolled, CPlayer::getVector(), i_menuHandle, myCheckList, PLAY_TREASURE_HUNT, Camera::position, ptrEmpty, ptrplayer, WIN_LOSE_MENU, winEaster, Vector3::x, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::DeclareGLEnable () private
Declares GLEnable.
Definition at line 805 of file SceneSP.cpp.
References LoadShaders(), m_parameters, m_programID, m_vertexArrayID, U_MVP, and U_NUMLIGHTS.
Referenced by Init().
void SceneSP::DeclareLightParameters () private
Declares all light parameters.
Definition at line 837 of file SceneSP.cpp.
References Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, Light::kC, Light::kL, Light::kQ, Light::LIGHT_POINT, Light::LIGHT_SPOT, lights, m_parameters, m_programID, Light::position, Light::power, Position::Set(), Color::Set(), Vector3::Set(), Light::spotDirection, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
Referenced by Init().
void SceneSP::DefineItem (CContainer * container, CItem item, int row) private
Defines all items and containers.
Parameters
container - the container to define
item - the item to define
row - the row of the container
Definition at line 755 of file SceneSP.cpp.
References CContainer::getFirstStock(), CItem::getGeoType(), CItem::getName(), CItem::getPrice(), CContainer::getSecondStock(), CContainer::getThirdStock(), CContainer::getXpos(), CContainer::getYpos(), CContainer::getZpos(), myStockList, ptrItem, RenderItemBottomRowXOffSet, RenderItemBottomRowYOffSet, RenderItemMiddleRowXOffSet, RenderItemMiddleRowYOffSet, RenderItemTopRowXOffSet, RenderItemTopRowYOffSet, ROW_BOTTOM, ROW_MIDDLE, and ROW_TOP.
Referenced by initShelves().
void SceneSP::Exit () virtual
Exits the scene.
Implements Scene.
Definition at line 5310 of file SceneSP.cpp.
References easter, m_programID, m_vertexArrayID, meshList, music, music2, NUM_GEOMETRY, ptrClass, ptrContainer, ptrItem, ptrNPC, ptrplayer, sound, and sf::SoundStream::stop().
void SceneSP::Init () virtual
Initialises the entire scene.
Implements Scene.
Definition at line 36 of file SceneSP.cpp.
References ambientSound, ATMMoney, b_crouching, b_dinged, b_inspection, b_is_Stealing, b_isWithinInteractionItem, b_isWithinPayingCashier, backgroundSound, caged, cagedPos, camera, Cashier, charactersrotation, closeEaster, CustomerinteractionTimer, DeclareGLEnable(), DeclareLightParameters(), diffX, diffY, diffZ, DRUNKIDLE, easterLimiter, easterLimiter2, easterTimer, elevatorDoorOpening, elevatorDoorY, elevatorIdle, elevatorSecondFloor, elevatorY, f_soundTimer, falling, getCaged, getCounter, getGabed, CPlayer::getItem(), CPlayer::getMaxItemCapacity(), getRicked, getTimed, getTrolled, handrotationleftandright, handtranslation, i_CashierAct, i_drunkmanAct, i_menuHandle, i_sampleItems, i_total_items_to_find, Camera3::Init(), initCharacter(), initGeoType(), initShelves(), inRange, interactionTimer, inventoryPointing, IsIntugofwar, itemXrotation, itemYrotation, MS::LoadMatrix(), LogisticinteractionTimer, LOOKATCUSTOMER, lose, MAIN_MENU, MENU_START, meshList, moveDoorBack, moveDoorFront, music, music2, NUM_GEOMETRY, sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, projectionStack, ptrInvSelect, ptrItem, ptrplayer, SceneSP::Transformations::rotateA, selectionPointing, sf::Listener::setGlobalVolume(), CPlayer::setInventory(), sf::SoundStream::setLoop(), sf::Listener::setPosition(), sf::SoundSource::setPosition(), Mtx44::SetToPerspective(), sf::SoundSource::setVolume(), showTuginstruction, toggleDoorBack, toggleDoorFront, toggleLight, SceneSP::Transformations::translateX, SceneSP::Transformations::translateY, SceneSP::Transformations::translateZ, trolleyrotation, win, winEaster, Vector3::x, Vector3::y, and Vector3::z.
Referenced by resetGame().
void SceneSP::initCharacter () private
Initialises the player and all NPCs.
Definition at line 351 of file SceneSP.cpp.
References BUILDING_GUY, CASHIER, CHATTING_GUY, CUSTOMER, DRUNKMAN, EASTER_EGG_GUY, GEO_CASHIER_ARM, GEO_CASHIER_HEADBODY, GEO_CASHIER_LEGANDFEET, GEO_DRUNKMAN_ARM, GEO_DRUNKMAN_HEADBODY, GEO_DRUNKMAN_LEGANDFEET, GEO_GHOSTNPC_ARM, GEO_GHOSTNPC_HEADANDBODY, GEO_GHOSTNPC_LEGANDFEET, GEO_LOGISTICSTAFF_ARM, GEO_LOGISTICSTAFF_HEADBODY, GEO_LOGISTICSTAFF_LEGANDFEET, GEO_NormalNpc1_ARM, GEO_NormalNpc1_HEADBODY, GEO_NormalNpc1_LEGANDFEET, GEO_NormalNpc2_ARM, GEO_NormalNpc2_HEADBODY, GEO_NormalNpc2_LEGANDFEET, GHOST_GUY, IDLE, IDLE_GUY, LOOKING_GUY, myNPCList, PART_TIME_WORKER, ptrNPC, ptrplayer, STATE_ACTIVE, STATE_FORWARD, STATE_IDLE, TUG_OF_WAR_GUY, WALKING, WALKING_GUY, WALKING_GUY_OUTSIDE_X, and WALKING_GUY_OUTSIDE_Z.
Referenced by Init().
void SceneSP::initGeoType () private
Initialises all geometry types.
Definition at line 158 of file SceneSP.cpp.
References MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_ATM, GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_BOX, GEO_BUILDING, GEO_CAGE, GEO_CAGEWALL, GEO_CAN_BEANS, GEO_CAN_BRAN, GEO_CAN_BROWN, GEO_CAN_GLUWATER, GEO_CAN_HUMANS, GEO_CAN_MELON, GEO_CAN_MTNDEW, GEO_CAN_PEAS, GEO_CAN_REDMONSTER, GEO_CAN_ROOTBEERFLOATS, GEO_CAN_SARDINE, GEO_CAN_SODA, GEO_CAN_SODAFEST, GEO_CAN_TOMATO, GEO_CAN_VARGA, GEO_CASHIER, GEO_CASHIER_ARM, GEO_CASHIER_HEADBODY, GEO_CASHIER_LEGANDFEET, GEO_CEREAL_1, GEO_CEREAL_2, GEO_CEREAL_3, GEO_CEREAL_4, GEO_CEREAL_5, GEO_DOOR, GEO_DRUNKMAN_ARM, GEO_DRUNKMAN_HEADBODY, GEO_DRUNKMAN_LEGANDFEET, GEO_EASTEREGG_1, GEO_EASTEREGG_2, GEO_EASTEREGG_3, GEO_EASTEREGG_4, GEO_EASTEREGG_5, GEO_EASTEREGG_6, GEO_ELEVATOR, GEO_ELEVATORDOOR, GEO_FENCE, GEO_FERRIS, GEO_FOODSHELF, GEO_FRONT, GEO_GABEN, GEO_GHOSTNPC_ARM, GEO_GHOSTNPC_HEADANDBODY, GEO_GHOSTNPC_LEGANDFEET, GEO_HANDS, GEO_ICEBOX, GEO_ITEM_SELECT, GEO_LEFT, GEO_LOGISTICSTAFF_ARM, GEO_LOGISTICSTAFF_HEADBODY, GEO_LOGISTICSTAFF_LEGANDFEET, GEO_MAIN_MENU_TITLE, GEO_MEATSHELF, GEO_NormalNpc1_ARM, GEO_NormalNpc1_HEADBODY, GEO_NormalNpc1_LEGANDFEET, GEO_NormalNpc2_ARM, GEO_NormalNpc2_HEADBODY, GEO_NormalNpc2_LEGANDFEET, GEO_OFFICECOMPUTER, GEO_RIGHT, GEO_SAMPLESTAND, GEO_SHELF, GEO_STORAGEANDOFFICE, GEO_SUPERMARKET, GEO_TEXT, GEO_TOP, GEO_TROLLEY, GEO_UI_SCREEN, GEO_WINEBOTTLE_1, GEO_WINEBOTTLE_2, GEO_WINEBOTTLE_3, GEO_WINEBOTTLE_4, GEO_WINEBOTTLE_5, LoadTGA(), meshList, and Mesh::textureID.
Referenced by Init().
void SceneSP::initNPC () private
void SceneSP::initShelves () private
Initialises all shelves in the scene.
Definition at line 487 of file SceneSP.cpp.
References DefineItem(), CContainer::getBottomItem(), CContainer::getMiddleItem(), CContainer::getTopItem(), myContainerList, myTreasureList, ptrClass, ptrContainer, ROW_BOTTOM, ROW_MIDDLE, and ROW_TOP.
Referenced by Init().
void SceneSP::Render () virtual
Renders the entire scene.
Implements Scene.
Definition at line 3300 of file SceneSP.cpp.
References camera, GAME_PLAYING, GEO_MAIN_MENU_TITLE, i_menuHandle, INSTRUCTION_MENU, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, lights, MS::LoadIdentity(), MS::LookAt(), m_parameters, MAIN_MENU, meshList, modelStack, PAUSE_MENU, Light::position, Camera::position, RenderBeerstand(), RenderBuilding(), RenderCharacters(), RenderEasteregg(), RenderFerrisWheel(), RenderHand(), RenderInstructionMenu(), RenderInventory(), RenderItem(), RenderMainMenu(), RenderPauseMenu(), RenderSkyBox(), RenderSubMenu(), RenderSupermarket(), RenderTGAUI(), RenderTug(), RenderUI(), RenderWinLoseMenu(), Light::spotDirection, SUB_MENU, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, WIN_LOSE_MENU, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneSP::RenderATM () private
Renders the ATM.
Definition at line 4174 of file SceneSP.cpp.
References camera, GEO_ATM, GEO_TEXT, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), MS::Rotate(), s_atm_balance, toggleLight, MS::Translate(), Vector3::x, and Vector3::z.
Referenced by RenderSupermarket().
void SceneSP::RenderBeerstand () private
Renders the beer stands.
Definition at line 4247 of file SceneSP.cpp.
References GEO_FOODSHELF, GEO_WINEBOTTLE_1, GEO_WINEBOTTLE_2, GEO_WINEBOTTLE_3, GEO_WINEBOTTLE_4, GEO_WINEBOTTLE_5, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), toggleLight, and MS::Translate().
Referenced by Render().
void SceneSP::RenderBuilding () private
Renders the buildings outside the supermarket.
Definition at line 4396 of file SceneSP.cpp.
References GEO_BUILDING, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by Render().
void SceneSP::RenderCage () private
Renders the "cage" easter egg.
Definition at line 4743 of file SceneSP.cpp.
References caged, cagedPos, GEO_CAGE, GEO_CAGEWALL, GEO_EASTEREGG_6, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), toggleLight, and MS::Translate().
Referenced by RenderEasteregg().
void SceneSP::RenderCashierTables () private
Renders the cashier tables in the scene.
Definition at line 3514 of file SceneSP.cpp.
References GEO_CASHIER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderCharacter (CNpc * npc) private
Function to render the targa inventory of the player.
Parameters
mesh - the mesh to render
size - the size of the mesh
x - the x position of the mesh
y - the y position of the mesh
Definition at line 3705 of file SceneSP.cpp.
References CNpc::getArmType(), CNpc::getHeadType(), CNpc::getLeftArm(), CNpc::getLeftLeg(), CNpc::getLegType(), CNpc::getRightArm(), CNpc::getRightLeg(), CCharacter::getXpos(), CNpc::getXRotation(), CCharacter::getYpos(), CNpc::getYRotation(), CCharacter::getZpos(), CNpc::getZRotation(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by RenderCharacters().
void SceneSP::RenderCharacters () private
Renders all Npcs.
Definition at line 3863 of file SceneSP.cpp.
References myNPCList, and RenderCharacter().
Referenced by Render().
void SceneSP::RenderDoors () private
Renders the front and back doors of the supermarket.
Definition at line 4079 of file SceneSP.cpp.
References GEO_DOOR, meshList, modelStack, moveDoorBack, moveDoorFront, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderDrunkmanUI () private
Renders the UI displayed when interacting with the drunk man Npc.
Definition at line 3272 of file SceneSP.cpp.
References camera, DRUNKCARRY, DRUNKIDLE, GEO_TEXT, i_drunkmanAct, meshList, Camera::position, RenderTextOnScreen(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by RenderUI().
void SceneSP::RenderEasteregg () private
Renders all easter eggs if in easter egg gamemode.
Definition at line 3158 of file SceneSP.cpp.
References GEO_TEXT, CCharacter::getCharacterJob(), inRange, meshList, PLAY_EASTER_EGG, ptrplayer, RenderCage(), RenderMiscEastereggs(), RenderTextOnScreen(), RenderTroll(), s_easter_count, s_easter_counter, winEaster, winEasterArray, winEasterArray1, and winEasterArray2.
Referenced by Render().
void SceneSP::RenderElevator () private
Renders the elevator in the scene.
Definition at line 3442 of file SceneSP.cpp.
References ElevatorDoorPosX, ElevatorDoorPosZ, elevatorDoorY, elevatorY, GEO_ELEVATOR, GEO_ELEVATORDOOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderElevatorPosX, RenderElevatorPosZ, RenderMesh(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderFence () private
Renders the fences in the scene.
Definition at line 3461 of file SceneSP.cpp.
References GEO_FENCE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderFerrisWheel () private
Renders the ferris wheel.
Definition at line 4382 of file SceneSP.cpp.
References GEO_FERRIS, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), toggleLight, and MS::Translate().
Referenced by Render().
void SceneSP::RenderFoodShelf () private
void SceneSP::RenderHand () private
Renders the player's hand.
Definition at line 3572 of file SceneSP.cpp.
References b_inspection, camera, emptyItem, GEO_HANDS, CItem::getGeoType(), CItem::getName(), handrotationleftandright, handtranslation, Application::IsKeyPressed(), itemXrotation, itemYrotation, meshList, modelStack, MS::PopMatrix(), Camera::position, ptrInvSelect, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, toggleLight, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneSP::RenderIceBox () private
Renders the ice boxes.
Definition at line 4193 of file SceneSP.cpp.
References GEO_ICEBOX, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderInstructionMenu () private
Renders the instruction menu.
Definition at line 3823 of file SceneSP.cpp.
References GEO_TEXT, MENU_BACK, menuTextArray, meshList, and RenderTextOnScreen().
Referenced by Render().
void SceneSP::RenderInventory () private
Renders the player's inventory.
Definition at line 4644 of file SceneSP.cpp.
References CPlayer::getItemHeld(), CPlayer::getVector(), meshList, ptrplayer, and RenderTGAInventory().
Referenced by Render().
void SceneSP::RenderItem () private
Renders the purchasable items in the supermarket.
Definition at line 4625 of file SceneSP.cpp.
References meshList, modelStack, myStockList, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), toggleLight, and MS::Translate().
Referenced by Render().
void SceneSP::RenderMainMenu () private
Renders the main menu.
Definition at line 3753 of file SceneSP.cpp.
References GEO_TEXT, MENU_EXIT, MENU_INSTRUCTIONS, MENU_START, menuTextArray, meshList, RenderTextOnScreen(), and selectionPointing.
Referenced by Render().
void SceneSP::RenderMeatShelf () private
Renders the meat shelves.
Definition at line 4218 of file SceneSP.cpp.
References GEO_MEATSHELF, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderMesh (Mesh * mesh, bool enableLight)
Renders a mesh.
Parameters
mesh - the mesh to be rendered
enableLight - enabling of light
Definition at line 3970 of file SceneSP.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by RenderATM(), RenderBeerstand(), RenderBuilding(), RenderCage(), RenderCashierTables(), RenderCharacter(), RenderDoors(), RenderElevator(), RenderFence(), RenderFerrisWheel(), RenderHand(), RenderIceBox(), RenderItem(), RenderMeatShelf(), RenderMiscEastereggs(), RenderOffice(), RenderReturnPoint(), RenderSamples(), RenderSamplestand(), RenderShelves(), RenderSkyBox(), RenderStorage(), RenderSupermarket(), RenderTGAInventory(), RenderTGAUI(), RenderTroll(), RenderTrolleys(), and RenderTug().
void SceneSP::RenderMiscEastereggs () private
Renders miscellaneous easter eggs.
Definition at line 3186 of file SceneSP.cpp.
References gabed, GEO_EASTEREGG_4, GEO_EASTEREGG_5, GEO_GABEN, meshList, modelStack, moveG, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), RenderTGAUI(), toggleLight, and MS::Translate().
Referenced by RenderEasteregg().
void SceneSP::RenderOffice () private
Renders the logistics staff office.
Definition at line 4657 of file SceneSP.cpp.
References GEO_OFFICECOMPUTER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderPauseMenu () private
Renders the pause menu.
Definition at line 3843 of file SceneSP.cpp.
References GEO_TEXT, MENU_BACK, MENU_RESUME, menuTextArray, meshList, RenderTextOnScreen(), and selectionPointing.
Referenced by Render().
void SceneSP::RenderReturnPoint () private
Renders the item return point.
Definition at line 4146 of file SceneSP.cpp.
References GEO_ICEBOX, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), returnPointBoxPosX, returnPointBoxPosY, returnPointBoxPosZ, toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderSamples () private
Renders the samples remaining on the sample stand.
Definition at line 4130 of file SceneSP.cpp.
References GEO_CAN_SARDINE, i_sampleItems, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), toggleLight, and MS::Translate().
Referenced by RenderSamplestand().
void SceneSP::RenderSamplestand () private
Renders the sample stand.
Definition at line 4159 of file SceneSP.cpp.
References GEO_SAMPLESTAND, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), RenderSamples(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderShelves () private
Function to render the shelves in the supermarket.
Definition at line 4049 of file SceneSP.cpp.
References myContainerList.
Referenced by RenderSupermarket().
void SceneSP::RenderShelves (CContainer * container) private
Overloaded function which takes in a container to render shelves.
Parameters
container - the container to take in
Definition at line 4065 of file SceneSP.cpp.
References GEO_SHELF, CContainer::getRotation(), CContainer::getXpos(), CContainer::getYpos(), CContainer::getZpos(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
void SceneSP::RenderSkyBox ()
Renders the sky box of the scene.
Definition at line 3386 of file SceneSP.cpp.
References camera, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), world_size, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneSP::RenderStorage () private
Renders the storage room.
Definition at line 4713 of file SceneSP.cpp.
References GEO_BOX, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by RenderSupermarket().
void SceneSP::RenderSubMenu () private
Renders the sub menu displaying the different gamemodes.
Definition at line 3778 of file SceneSP.cpp.
References GEO_TEXT, MENU_EASTER_EGG_HUNT, MENU_FREE_ROAM, MENU_TREASURE_HUNT, menuTextArray, meshList, RenderTextOnScreen(), and selectionPointing.
Referenced by Render().
void SceneSP::RenderSupermarket () private
Renders the entire supermarket.
Definition at line 4020 of file SceneSP.cpp.
References GEO_STORAGEANDOFFICE, GEO_SUPERMARKET, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderATM(), RenderCashierTables(), RenderDoors(), RenderElevator(), RenderFence(), RenderIceBox(), RenderMeatShelf(), RenderMesh(), RenderOffice(), RenderReturnPoint(), RenderSamplestand(), RenderShelves(), RenderStorage(), RenderTrolleys(), and toggleLight.
Referenced by Render().
void SceneSP::RenderText (Mesh * mesh, std::string text, Color color) private
Renders text in world space on a mesh.
Parameters
mesh - the mesh to be rendered
text - the text to be rendered
color - the color of the text to be rendered
Definition at line 3881 of file SceneSP.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneSP::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text on screen.
Parameters
mesh - the mesh to be rendered
text - the text to be rendered
color - the color of the text to be rendered
size - the size of the text
x - x position of the text
y - y position of the text
Definition at line 3920 of file SceneSP.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by RenderATM(), RenderDrunkmanUI(), RenderEasteregg(), RenderInstructionMenu(), RenderMainMenu(), RenderPauseMenu(), RenderSubMenu(), RenderTroll(), RenderTugofwarUI(), RenderUI(), and RenderWinLoseMenu().
void SceneSP::RenderTGAInventory (Mesh * mesh, float size, float x, float y) private
Function to render the targa inventory of the player.
Parameters
mesh - the mesh to render
size - the size of the mesh
x - the x position of the mesh
y - the y position of the mesh
Definition at line 3664 of file SceneSP.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), U_LIGHTENABLED, U_TEXT_ENABLED, and viewStack.
Referenced by RenderInventory(), and RenderUI().
void SceneSP::RenderTGAUI (Mesh * mesh, float size, float x, float y) private
Function to render the targa UI of the player.
Parameters
mesh - the mesh to render
size - the size of the mesh
x - the x position of the mesh
y - the y position of the mesh
Definition at line 3623 of file SceneSP.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), U_LIGHTENABLED, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderMiscEastereggs(), and RenderUI().
void SceneSP::RenderTroll () private
Renders the "troll" easter egg.
Definition at line 4803 of file SceneSP.cpp.
References GEO_EASTEREGG_3, GEO_TEXT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), RenderTextOnScreen(), reversed, toggleLight, and MS::Translate().
Referenced by RenderEasteregg().
void SceneSP::RenderTrolleys () private
Renders the trolleys in the scene.
Definition at line 3540 of file SceneSP.cpp.
References camera, GEO_TROLLEY, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, MS::Translate(), trolleyrotation, Vector3::x, and Vector3::z.
Referenced by RenderSupermarket().
void SceneSP::RenderTug () private
Renders the tug of war activity.
Definition at line 4608 of file SceneSP.cpp.
References GEO_CAN_SARDINE, IsIntugofwar, meshList, modelStack, myNPCList, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), toggleLight, and MS::Translate().
Referenced by Render().
void SceneSP::RenderTugofwarUI () private
Renders the UI displayed while in the tug of war activity.
Definition at line 3250 of file SceneSP.cpp.
References camera, GEO_TEXT, IsIntugofwar, lose, meshList, Camera::position, RenderTextOnScreen(), showTuginstruction, win, Vector3::x, Vector3::y, and Vector3::z.
Referenced by RenderUI().
void SceneSP::RenderUI () private
Renders the player's UI.
Definition at line 3205 of file SceneSP.cpp.
References b_inspection, b_isWithinInteractionItem, b_isWithinPayingCashier, checkReturnPoint(), GEO_ITEM_SELECT, GEO_TEXT, GEO_UI_SCREEN, CCharacter::getCharacterJob(), CPlayer::getItem(), CItem::getName(), i_total_items_to_find, inventoryPointing, meshList, myCheckList, PLAY_TREASURE_HUNT, ptrEmpty, ptrplayer, RenderDrunkmanUI(), RenderTextOnScreen(), RenderTGAInventory(), RenderTGAUI(), RenderTugofwarUI(), s_fps, s_item_name, s_item_price, s_money, and s_UI_Play_Mode.
Referenced by Render().
void SceneSP::RenderWinLoseMenu () private
Renders the win / lose menu.
Definition at line 3803 of file SceneSP.cpp.
References b_is_Stealing, GEO_TEXT, MENU_BACK, menuTextArray, meshList, and RenderTextOnScreen().
Referenced by Render().
void SceneSP::resetGame () private
Resets the entire game.
Definition at line 1404 of file SceneSP.cpp.
References Init(), myCheckList, myContainerList, myNPCList, myStockList, and myTreasureList.
Referenced by UpdatePauseMenu(), and UpdateWinLoseMenu().
void SceneSP::Update (double dt) virtual
Updates the entire scene.
Parameters
dt - delta time
Implements Scene.
Definition at line 1635 of file SceneSP.cpp.
References CustomerinteractionTimer, f_soundTimer, GAME_PLAYING, i_menuHandle, interactionTimer, LogisticinteractionTimer, UpdateAITimer(), UpdateMenu(), and UpdatePlaying().
void SceneSP::UpdateAI (double dt) private
Updates the movement of all Npcs in the scene based on dt.
Parameters
dt - delta time
Definition at line 986 of file SceneSP.cpp.
References UpdateBuildingGuy(), UpdateChattingman(), UpdateCustomer(), UpdateDrunkmanguy(), UpdateGhostman(), UpdateLegAnimation(), UpdateLogisticman(), UpdateLookingman(), UpdateShoppers(), UpdateTugofwarguy(), UpdateWalkingman(), UpdateWalkingmanoutsideX(), and UpdateWalkingmanoutsideZ().
Referenced by UpdatePlaying().
void SceneSP::UpdateAITimer (double dt) private
Updates the Npcs interaction timers based on dt.
Parameters
dt - delta time
Definition at line 1620 of file SceneSP.cpp.
References myNPCList.
Referenced by Update().
void SceneSP::UpdateATM () private
Updates the addition of the player's money and deduction of the ATM's money.
Definition at line 1769 of file SceneSP.cpp.
References ATMMoney, camera, CPlayer::getMoney(), interactionTimer, interactionTimerLimiter, Application::IsKeyPressed(), Camera::position, ptrplayer, s_atm_balance, CPlayer::setMoney(), Vector3::x, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateBuildingGuy (double dt) private
Updates the movement of BuildingGuy Npc based on dt.
Parameters
dt - delta time
Definition at line 1047 of file SceneSP.cpp.
References BUILDING_GUY, camera, falling, myNPCList, Camera::position, STATE_FORWARD, STATE_IDLE, STATE_JUMP, Vector3::x, and Vector3::z.
Referenced by UpdateAI().
void SceneSP::UpdateCage (double dt) private
Updates the "cage" easter egg based on dt.
Parameters
dt - delta time
Definition at line 2960 of file SceneSP.cpp.
References caged, cagedPos, camera, diffX, diffY, diffZ, easter, easterLimiter, easterTimer, getCaged, getCounter, Application::IsKeyPressed(), sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, resetValue, sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), soundFXArray, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdateEasteregg().
void SceneSP::UpdateChattingman (double dt) private
Updates the movement of the chatting Npc based on dt.
Parameters
dt - delta time
Definition at line 2734 of file SceneSP.cpp.
References CHATTING_GUY, IDLE, IDLE_GUY, myNPCList, NPCLookLimiter, STATE_BACKWARD, STATE_FORWARD, STATE_IDLE, STATE_LEFT, STATE_RIGHT, and WALKING.
Referenced by UpdateAI().
void SceneSP::UpdateCustomer (double dt) private
Updates the movement of the customers based on dt.
Parameters
dt - delta time
Definition at line 2584 of file SceneSP.cpp.
References CASHIER, CUSTOMER, CustomerinteractionTimer, i_CashierAct, IDLE, LOOKATCUSTOMER, LOOKATITEM, LOOKATSCREEN, myNPCList, STATE_ACTIVE, STATE_BACKWARD, STATE_FORWARD, STATE_IDLE, STATE_INTOBUILDING, STATE_LEFT, STATE_REACTIVATE, STATE_RIGHT, WALKING, and WalkingNpcInitArm.
Referenced by UpdateAI().
void SceneSP::UpdateDoor (double dt) private
Updates the opening and closing of the front and back doors based on dt.
Parameters
dt - delta time
Definition at line 1797 of file SceneSP.cpp.
References camera, f_soundTimer, moveDoorBack, moveDoorFront, myNPCList, sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), sound, soundFXArray, soundLimiter, toggleDoorBack, toggleDoorFront, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateDrunkman (double dt) private
Updates the picking up of the Drunkman Npc based on dt.
Parameters
dt - delta time
Definition at line 2141 of file SceneSP.cpp.
References camera, DRUNKCARRY, DRUNKIDLE, DRUNKMAN, DRUNKOUTSIDE, i_drunkmanAct, Application::IsKeyPressed(), myNPCList, Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateDrunkmanguy (double dt) private
Updates the movement of the Drunkman Npc based on dt.
Parameters
dt - delta time
Definition at line 2174 of file SceneSP.cpp.
References camera, DRUNKCARRY, DRUNKIDLE, DRUNKMAN, i_drunkmanAct, myNPCList, Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdateAI().
void SceneSP::UpdateEasteregg (double dt) private
Updates all easter eggs in the easter egg gamemode.
Parameters
dt - delta time
Definition at line 1453 of file SceneSP.cpp.
References closeEaster, easterTimer, CCharacter::getCharacterJob(), getCounter, Application::IsKeyPressed(), numEastereggs, PLAY_EASTER_EGG, ptrplayer, s_easter_count, s_easter_counter, UpdateCage(), UpdateGaben(), UpdateMiscEasteregg(), UpdateTroll(), and winEaster.
Referenced by UpdatePlaying().
void SceneSP::UpdateEasterEggGuy (double dt) private
Updates the movement of EasterEggGuy Npc based on dt.
Parameters
dt - delta time
Definition at line 1011 of file SceneSP.cpp.
References camera, EASTER_EGG_GUY, Application::IsKeyPressed(), myNPCList, Camera::position, Vector3::x, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateElevator (double dt) private
Updates the movement of the elevator based on dt.
Parameters
dt - delta time
Definition at line 1662 of file SceneSP.cpp.
References b_dinged, camera, checkElevatorXposMax, checkElevatorXposMin, checkElevatorYposMax, checkElevatorYposMin, checkElevatorZposMax, checkElevatorZposMin, checkInnerElevatorXposMax, checkInnerElevatorXposMin, checkInnerElevatorZposMax, checkInnerElevatorZposMin, elevatorDoorOpening, elevatorDoorY, elevatorIdle, elevatorSecondFloor, elevatorSpeed, elevatorY, interactionTimer, interactionTimerLimiter, Application::IsKeyPressed(), sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, secondFloorYpositionMax, secondFloorYpositionMin, sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), sound, soundFXArray, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateGaben (double dt) private
Updates the "gabe" easter egg based on dt.
Parameters
dt - delta time
Definition at line 3020 of file SceneSP.cpp.
References easter, gabed, getCounter, getGabed, Application::IsKeyPressed(), moveG, sf::Music::openFromFile(), sf::SoundStream::play(), sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), soundFXArray, and summonG.
Referenced by UpdateEasteregg().
void SceneSP::UpdateGhostman (double dt) private
Updates the movement of the Ghost Npc based on dt.
Parameters
dt - delta time
Definition at line 2342 of file SceneSP.cpp.
References camera, GHOST_GUY, GhostNpcAppearBoundX1, GhostNpcAppearBoundX2, GhostNpcAppearBoundZ1, GhostNpcAppearBoundZ2, GhostNpcAppearBoundZ3, GhostNpcInitLeg, GhostNpcInitRot, GhostNpcMoveBoundX1, GhostNpcMoveBoundX2, GhostNpcMoveBoundY1, GhostNpcMoveBoundY2, GhostNpcResetYPos, myNPCList, Camera::position, STATE_FORWARD, STATE_IDLE, Vector3::x, and Vector3::z.
Referenced by UpdateAI().
void SceneSP::UpdateHand (double dt) private
Updates the player's hand movement based on dt.
Parameters
dt - delta time
Definition at line 1104 of file SceneSP.cpp.
References camera, Camera3::CAMERA_SPEED, handrotationleftandright, handtranslation, Application::IsKeyPressed(), PunchTimerLimiter, and reversed.
Referenced by UpdatePlaying().
void SceneSP::UpdateInstructionMenu () private
Updates the instruction menu.
Definition at line 1293 of file SceneSP.cpp.
References i_menuHandle, interactionTimer, Application::IsKeyPressed(), MAIN_MENU, MENU_BACK, MENU_START, menuTImerLimiter, and selectionPointing.
Referenced by UpdateMenu().
void SceneSP::UpdateItemInspection () private
Updates the inspection of items.
Definition at line 967 of file SceneSP.cpp.
References b_inspection, and Application::IsKeyPressed().
Referenced by UpdatePlaying().
void SceneSP::UpdateItemRotation (double dt) private
Updates the item rotation based on dt.
Parameters
dt - delta time
Definition at line 1421 of file SceneSP.cpp.
References Application::IsKeyPressed(), itemRotationSpeedMultiplyer, itemXrotation, and itemYrotation.
Referenced by UpdatePlaying().
void SceneSP::UpdateLegAnimation (double dt) private
Updates the leg animation of all Npcs while they are moving based on dt.
Parameters
dt - delta time
Definition at line 2931 of file SceneSP.cpp.
References maxlegRot, myNPCList, spdMod, and WALKING.
Referenced by UpdateAI().
void SceneSP::UpdateLogisticman (double dt) private
Updates the movement of the logistics Npc based on dt.
Parameters
dt - delta time
Definition at line 2512 of file SceneSP.cpp.
References IDLE, LogisticinteractionTimer, myNPCList, NPCLookLimiter, PART_TIME_WORKER, STATE_ACTIVE, STATE_BACKWARD, STATE_FORWARD, STATE_IDLE, WALKING, and WalkingNpcInitArm.
Referenced by UpdateAI().
void SceneSP::UpdateLookingman (double dt) private
Updates the movement of the Npc looking at items based on dt.
Parameters
dt - delta time
Definition at line 2415 of file SceneSP.cpp.
References IDLE, LOOKING_GUY, myNPCList, NPCLookLimiter, STATE_BACKWARD, STATE_FORWARD, STATE_IDLE, STATE_LEFT, STATE_RIGHT, and WALKING.
Referenced by UpdateAI().
void SceneSP::UpdateMainMenu () private
Updates the main menu upon starting up.
Definition at line 1143 of file SceneSP.cpp.
References i_menuHandle, INSTRUCTION_MENU, interactionTimer, Application::IsKeyPressed(), MENU_BACK, MENU_EXIT, MENU_FREE_ROAM, MENU_INSTRUCTIONS, MENU_START, menuTImerLimiter, selectionPointing, and SUB_MENU.
Referenced by UpdateMenu().
void SceneSP::UpdateMenu () private
Updates the switching between menus.
Definition at line 1316 of file SceneSP.cpp.
References i_menuHandle, INSTRUCTION_MENU, MAIN_MENU, PAUSE_MENU, SUB_MENU, UpdateInstructionMenu(), UpdateMainMenu(), UpdatePauseMenu(), UpdateStartMenu(), UpdateWinLoseMenu(), and WIN_LOSE_MENU.
Referenced by Update().
void SceneSP::UpdateMiscEasteregg (double dt) private
Updates the miscellaneous easter eggs based on dt.
Parameters
dt - delta time
Definition at line 3101 of file SceneSP.cpp.
References camera, easter, easterLimiter, easterTimer, getCounter, getRicked, getTimed, inRange, Application::IsKeyPressed(), sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), soundFXArray, Vector3::x, and Vector3::z.
Referenced by UpdateEasteregg().
void SceneSP::UpdatePauseMenu () private
Updates the pause menu.
Definition at line 1349 of file SceneSP.cpp.
References GAME_PLAYING, i_menuHandle, interactionTimer, Application::IsKeyPressed(), MENU_BACK, MENU_RESUME, menuTImerLimiter, resetGame(), and selectionPointing.
Referenced by UpdateMenu().
void SceneSP::UpdatePaying () private
Updates the paying of money.
Definition at line 1979 of file SceneSP.cpp.
References b_isWithinPayingCashier, camera, clearText, CPlayer::getItem(), CPlayer::getMoney(), CPlayer::getVector(), interactionTimer, interactionTimerLimiter, inventoryPointing, Application::IsKeyPressed(), myCheckList, Camera::position, ptrEmpty, ptrInvSelect, ptrplayer, CPlayer::setInventory(), CPlayer::setMoney(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdatePlayerSelection () private
Updates the selection of inventory slot by the player.
Definition at line 1897 of file SceneSP.cpp.
References CPlayer::getItem(), CPlayer::getItemHeld(), CItem::getName(), inventoryPointing, Application::IsKeyPressed(), ptrInvSelect, and ptrplayer.
Referenced by UpdatePlaying().
void SceneSP::UpdatePlaying (double dt) private
Updates the scene when the player is ingame.
Parameters
dt - delta time
Definition at line 1486 of file SceneSP.cpp.
References ambientSound, b_crouching, caged, camera, checkCollision(), checkPickUpItem(), checkReturnPoint(), checkWinLose(), easterLimiter2, easterTimer, elevatorIdle, sf::SoundStream::getStatus(), i_menuHandle, IsIntugofwar, Application::IsKeyPressed(), MENU_RESUME, music, sf::Music::openFromFile(), PAUSE_MENU, sf::SoundStream::play(), Camera::position, reversed, reverseTimer, selectionPointing, sf::Listener::setGlobalVolume(), sf::SoundStream::setLoop(), sf::Listener::setPosition(), sf::SoundSource::setPosition(), sf::SoundSource::setVolume(), soundFXArray, Camera::target, toggleLight, UpdateAI(), UpdateATM(), UpdateDoor(), UpdateDrunkman(), UpdateEasteregg(), UpdateEasterEggGuy(), UpdateElevator(), UpdateHand(), UpdateItemInspection(), UpdateItemRotation(), Camera3::UpdateMovement(), UpdatePaying(), UpdatePlayerSelection(), UpdateSamples(), UpdateTugofwar(), UpdateUI(), Camera3::UpdateView(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SceneSP::UpdateSamples () private
Updates the remaining samples on the sample stand.
Definition at line 2030 of file SceneSP.cpp.
References camera, i_sampleItems, interactionTimer, interactionTimerLimiter, Application::IsKeyPressed(), sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), sound, soundFXArray, Vector3::x, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateShoppers (double dt) private
Updates the movement of the shoppers based on dt.
Parameters
dt - delta time
Definition at line 2818 of file SceneSP.cpp.
References CUSTOMER, IDLE, LOOKING_GUY, myNPCList, SHOPPERS, STATE_ACTIVE, STATE_BACKWARD, STATE_FORWARD, STATE_IDLE, STATE_LEFT, STATE_REACTIVATE, STATE_RIGHT, and WALKING.
Referenced by UpdateAI().
void SceneSP::UpdateStartMenu () private
Updates the Start menu.
Definition at line 1199 of file SceneSP.cpp.
References GAME_PLAYING, i_menuHandle, i_total_items_to_find, interactionTimer, Application::IsKeyPressed(), MENU_EASTER_EGG_HUNT, MENU_FREE_ROAM, MENU_TREASURE_HUNT, menuTImerLimiter, music, myCheckList, myTreasureList, PLAY_EASTER_EGG, PLAY_FREE_ROAM, PLAY_TREASURE_HUNT, ptrplayer, selectionPointing, CCharacter::setCharacterJob(), and sf::SoundStream::stop().
Referenced by UpdateMenu().
void SceneSP::UpdateTroll (double dt) private
Updates the "troll" easter egg based on dt.
Parameters
dt - delta time
Definition at line 3063 of file SceneSP.cpp.
References camera, easter, easterLimiter, easterTimer, getCounter, getTrolled, Application::IsKeyPressed(), sf::Music::openFromFile(), sf::SoundStream::play(), Camera::position, resetValue, reversed, reverseLimiter, reverseTimer, sf::SoundStream::setLoop(), sf::SoundSource::setVolume(), soundFXArray, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdateEasteregg().
void SceneSP::UpdateTugofwar (double dt) private
Updates the player during the tug of war activity based on dt.
Parameters
dt - delta time
Definition at line 2059 of file SceneSP.cpp.
References camera, Camera3::CAMERA_SPEED, diffX, diffZ, interactionTimer, IsIntugofwar, Application::IsKeyPressed(), lose, Camera::position, showTuginstruction, Camera::target, TugofwarTimerLimiter, win, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateTugofwarguy (double dt) private
Updates the Npc involves in the tug of war activity based on dt.
Parameters
dt - delta time
Definition at line 2115 of file SceneSP.cpp.
References camera, IsIntugofwar, myNPCList, Camera::position, Vector3::x, and Vector3::z.
Referenced by UpdateAI().
void SceneSP::UpdateUI (double dt) private
Updates the players UI.
Parameters
dt - delta time
Definition at line 941 of file SceneSP.cpp.
References camera, CPlayer::getItem(), CPlayer::getMoney(), CItem::getPrice(), inventoryPointing, Camera::position, ptrplayer, s_camera_target, s_fps, s_item_price, s_money, s_position, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by UpdatePlaying().
void SceneSP::UpdateWalkingman (double dt) private
Updates the movement of the Npcs walking inside the supermarket based on dt.
Parameters
dt - delta time
Definition at line 2284 of file SceneSP.cpp.
References myNPCList, STATE_BACKWARD, STATE_FORWARD, STATE_LEFT, STATE_RIGHT, WALKING, WALKING_GUY, and WalkingNpcInitArm.
Referenced by UpdateAI().
void SceneSP::UpdateWalkingmanoutsideX (double dt) private
Updates the movement of the Passer-by Npcs outside the supermarket moving in the X direction based on dt.
Parameters
dt - delta time
Definition at line 2208 of file SceneSP.cpp.
References myNPCList, STATE_BACKWARD, STATE_FORWARD, and WALKING_GUY_OUTSIDE_X.
Referenced by UpdateAI().
void SceneSP::UpdateWalkingmanoutsideZ (double dt) private
Updates the movement of the Passer-by Npcs outside the supermarket moving in the Z direction based on dt.
Parameters
dt - delta time
Definition at line 2245 of file SceneSP.cpp.
References myNPCList, STATE_BACKWARD, STATE_FORWARD, and WALKING_GUY_OUTSIDE_Z.
Referenced by UpdateAI().
void SceneSP::UpdateWinLoseMenu () private
Updates the win / lose menu.
Definition at line 1273 of file SceneSP.cpp.
References Application::IsKeyPressed(), MENU_BACK, resetGame(), and selectionPointing.
Referenced by UpdateMenu().
Field Documentation
float SceneSP::ATMMoney private
Definition at line 181 of file SceneSP.h.
Referenced by Init(), and UpdateATM().
bool SceneSP::b_crouching private
Definition at line 203 of file SceneSP.h.
Referenced by Init(), and UpdatePlaying().
bool SceneSP::b_dinged private
Definition at line 164 of file SceneSP.h.
Referenced by Init(), and UpdateElevator().
bool SceneSP::b_inspection private
Definition at line 204 of file SceneSP.h.
Referenced by Init(), RenderHand(), RenderUI(), and UpdateItemInspection().
bool SceneSP::b_is_Stealing private
Definition at line 163 of file SceneSP.h.
Referenced by checkWinLose(), Init(), and RenderWinLoseMenu().
bool SceneSP::b_isWithinInteractionItem private
Definition at line 161 of file SceneSP.h.
Referenced by checkPickUpItem(), Init(), and RenderUI().
bool SceneSP::b_isWithinPayingCashier private
Definition at line 162 of file SceneSP.h.
Referenced by Init(), RenderUI(), and UpdatePaying().
bool SceneSP::caged private
Definition at line 199 of file SceneSP.h.
Referenced by Init(), RenderCage(), UpdateCage(), and UpdatePlaying().
float SceneSP::cagedPos private
Definition at line 188 of file SceneSP.h.
Referenced by Init(), RenderCage(), and UpdateCage().
Camera3 SceneSP::camera
Definition at line 257 of file SceneSP.h.
Referenced by checkElevatorCollision(), checkObjectCollision(), checkPickUpItem(), checkReturnPoint(), checkSupermarketCollision(), checkWinLose(), Init(), Render(), RenderATM(), RenderDrunkmanUI(), RenderHand(), RenderSkyBox(), RenderTrolleys(), RenderTugofwarUI(), UpdateATM(), UpdateBuildingGuy(), UpdateCage(), UpdateDoor(), UpdateDrunkman(), UpdateDrunkmanguy(), UpdateEasterEggGuy(), UpdateElevator(), UpdateGhostman(), UpdateHand(), UpdateMiscEasteregg(), UpdatePaying(), UpdatePlaying(), UpdateSamples(), UpdateTroll(), UpdateTugofwar(), UpdateTugofwarguy(), and UpdateUI().
Transformations SceneSP::Cashier
Definition at line 265 of file SceneSP.h.
Referenced by Init().
float SceneSP::charactersrotation private
Definition at line 176 of file SceneSP.h.
Referenced by Init().
bool SceneSP::closeEaster private
Definition at line 192 of file SceneSP.h.
Referenced by checkWinLose(), Init(), and UpdateEasteregg().
float SceneSP::CustomerinteractionTimer private
Definition at line 168 of file SceneSP.h.
Referenced by Init(), Update(), and UpdateCustomer().
float SceneSP::diffX private
Definition at line 174 of file SceneSP.h.
Referenced by checkElevatorCollision(), checkObjectCollision(), checkSupermarketCollision(), Init(), UpdateCage(), and UpdateTugofwar().
float SceneSP::diffY private
Definition at line 189 of file SceneSP.h.
Referenced by Init(), and UpdateCage().
float SceneSP::diffZ private
Definition at line 175 of file SceneSP.h.
Referenced by checkElevatorCollision(), checkObjectCollision(), checkSupermarketCollision(), Init(), UpdateCage(), and UpdateTugofwar().
sf::Music SceneSP::easter private
Definition at line 246 of file SceneSP.h.
Referenced by Exit(), UpdateCage(), UpdateGaben(), UpdateMiscEasteregg(), and UpdateTroll().
float SceneSP::easterLimiter private
Definition at line 185 of file SceneSP.h.
Referenced by Init(), UpdateCage(), UpdateMiscEasteregg(), and UpdateTroll().
float SceneSP::easterLimiter2 private
Definition at line 186 of file SceneSP.h.
Referenced by Init(), and UpdatePlaying().
float SceneSP::easterTimer private
Definition at line 187 of file SceneSP.h.
Referenced by Init(), UpdateCage(), UpdateEasteregg(), UpdateMiscEasteregg(), UpdatePlaying(), and UpdateTroll().
bool SceneSP::elevatorDoorOpening private
Definition at line 159 of file SceneSP.h.
Referenced by checkElevatorCollision(), Init(), and UpdateElevator().
float SceneSP::elevatorDoorY private
Definition at line 177 of file SceneSP.h.
Referenced by Init(), RenderElevator(), and UpdateElevator().
bool SceneSP::elevatorIdle private
Definition at line 210 of file SceneSP.h.
Referenced by Init(), UpdateElevator(), and UpdatePlaying().
bool SceneSP::elevatorSecondFloor private
Definition at line 160 of file SceneSP.h.
Referenced by Init(), and UpdateElevator().
float SceneSP::elevatorY private
Definition at line 178 of file SceneSP.h.
Referenced by Init(), RenderElevator(), and UpdateElevator().
CEmptyItem SceneSP::emptyItem private
Definition at line 184 of file SceneSP.h.
Referenced by checkPickUpItem(), checkReturnPoint(), and RenderHand().
float SceneSP::f_soundTimer private
Definition at line 182 of file SceneSP.h.
Referenced by Init(), Update(), and UpdateDoor().
bool SceneSP::falling private
Definition at line 165 of file SceneSP.h.
Referenced by Init(), and UpdateBuildingGuy().
bool SceneSP::getCaged private
Definition at line 194 of file SceneSP.h.
Referenced by checkWinLose(), Init(), and UpdateCage().
int SceneSP::getCounter private
Definition at line 190 of file SceneSP.h.
Referenced by checkWinLose(), Init(), UpdateCage(), UpdateEasteregg(), UpdateGaben(), UpdateMiscEasteregg(), and UpdateTroll().
bool SceneSP::getGabed private
Definition at line 195 of file SceneSP.h.
Referenced by checkWinLose(), Init(), and UpdateGaben().
bool SceneSP::getRicked private
Definition at line 198 of file SceneSP.h.
Referenced by Init(), and UpdateMiscEasteregg().
bool SceneSP::getTimed private
Definition at line 197 of file SceneSP.h.
Referenced by checkWinLose(), Init(), and UpdateMiscEasteregg().
bool SceneSP::getTrolled private
Definition at line 196 of file SceneSP.h.
Referenced by checkWinLose(), Init(), and UpdateTroll().
float SceneSP::handrotationleftandright private
Definition at line 172 of file SceneSP.h.
Referenced by Init(), RenderHand(), and UpdateHand().
float SceneSP::handtranslation private
Definition at line 173 of file SceneSP.h.
Referenced by Init(), RenderHand(), and UpdateHand().
int SceneSP::i_CashierAct private
Definition at line 209 of file SceneSP.h.
Referenced by Init(), and UpdateCustomer().
int SceneSP::i_drunkmanAct private
Definition at line 208 of file SceneSP.h.
Referenced by Init(), RenderDrunkmanUI(), UpdateDrunkman(), and UpdateDrunkmanguy().
int SceneSP::i_menuHandle private
Definition at line 207 of file SceneSP.h.
Referenced by checkWinLose(), Init(), Render(), Update(), UpdateInstructionMenu(), UpdateMainMenu(), UpdateMenu(), UpdatePauseMenu(), UpdatePlaying(), and UpdateStartMenu().
int SceneSP::i_sampleItems private
Definition at line 206 of file SceneSP.h.
Referenced by Init(), RenderSamples(), and UpdateSamples().
int SceneSP::i_total_items_to_find private
Definition at line 205 of file SceneSP.h.
Referenced by Init(), RenderUI(), and UpdateStartMenu().
bool SceneSP::inRange private
Definition at line 193 of file SceneSP.h.
Referenced by Init(), RenderEasteregg(), and UpdateMiscEasteregg().
float SceneSP::interactionTimer private
Definition at line 166 of file SceneSP.h.
Referenced by addToInventory(), checkPickUpItem(), checkReturnPoint(), Init(), Update(), UpdateATM(), UpdateElevator(), UpdateInstructionMenu(), UpdateMainMenu(), UpdatePauseMenu(), UpdatePaying(), UpdateSamples(), UpdateStartMenu(), and UpdateTugofwar().
int SceneSP::inventoryPointing private
Definition at line 227 of file SceneSP.h.
Referenced by addToInventory(), checkPickUpItem(), checkReturnPoint(), Init(), RenderUI(), UpdatePaying(), UpdatePlayerSelection(), and UpdateUI().
bool SceneSP::IsIntugofwar private
Definition at line 211 of file SceneSP.h.
Referenced by Init(), RenderTug(), RenderTugofwarUI(), UpdatePlaying(), UpdateTugofwar(), and UpdateTugofwarguy().
float SceneSP::itemXrotation private
Definition at line 180 of file SceneSP.h.
Referenced by Init(), RenderHand(), and UpdateItemRotation().
float SceneSP::itemYrotation private
Definition at line 179 of file SceneSP.h.
Referenced by Init(), RenderHand(), and UpdateItemRotation().
Light SceneSP::lights[2]
Definition at line 264 of file SceneSP.h.
Referenced by DeclareLightParameters(), and Render().
float SceneSP::LogisticinteractionTimer private
Definition at line 167 of file SceneSP.h.
Referenced by Init(), Update(), and UpdateLogisticman().
bool SceneSP::lose private
Definition at line 201 of file SceneSP.h.
Referenced by Init(), RenderTugofwarUI(), and UpdateTugofwar().
unsigned SceneSP::m_parameters[U_TOTAL] private
Definition at line 153 of file SceneSP.h.
Referenced by DeclareGLEnable(), DeclareLightParameters(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), RenderTGAInventory(), and RenderTGAUI().
unsigned SceneSP::m_programID private
Definition at line 152 of file SceneSP.h.
Referenced by DeclareGLEnable(), DeclareLightParameters(), and Exit().
unsigned SceneSP::m_vertexArrayID private
Definition at line 150 of file SceneSP.h.
Referenced by DeclareGLEnable(), and Exit().
Mesh* SceneSP::meshList[NUM_GEOMETRY] private
Definition at line 151 of file SceneSP.h.
Referenced by Exit(), Init(), initGeoType(), Render(), RenderATM(), RenderBeerstand(), RenderBuilding(), RenderCage(), RenderCashierTables(), RenderCharacter(), RenderDoors(), RenderDrunkmanUI(), RenderEasteregg(), RenderElevator(), RenderFence(), RenderFerrisWheel(), RenderHand(), RenderIceBox(), RenderInstructionMenu(), RenderInventory(), RenderItem(), RenderMainMenu(), RenderMeatShelf(), RenderMiscEastereggs(), RenderOffice(), RenderPauseMenu(), RenderReturnPoint(), RenderSamples(), RenderSamplestand(), RenderShelves(), RenderSkyBox(), RenderStorage(), RenderSubMenu(), RenderSupermarket(), RenderTroll(), RenderTrolleys(), RenderTug(), RenderTugofwarUI(), RenderUI(), and RenderWinLoseMenu().
MS SceneSP::modelStack
Definition at line 262 of file SceneSP.h.
Referenced by Render(), RenderATM(), RenderBeerstand(), RenderBuilding(), RenderCage(), RenderCashierTables(), RenderCharacter(), RenderDoors(), RenderElevator(), RenderFence(), RenderFerrisWheel(), RenderHand(), RenderIceBox(), RenderItem(), RenderMeatShelf(), RenderMesh(), RenderMiscEastereggs(), RenderOffice(), RenderReturnPoint(), RenderSamples(), RenderSamplestand(), RenderShelves(), RenderSkyBox(), RenderStorage(), RenderSupermarket(), RenderText(), RenderTextOnScreen(), RenderTGAInventory(), RenderTGAUI(), RenderTroll(), RenderTrolleys(), and RenderTug().
float SceneSP::moveDoorBack private
Definition at line 170 of file SceneSP.h.
Referenced by Init(), RenderDoors(), and UpdateDoor().
float SceneSP::moveDoorFront private
Definition at line 169 of file SceneSP.h.
Referenced by Init(), RenderDoors(), and UpdateDoor().
sf::Music SceneSP::music private
Definition at line 243 of file SceneSP.h.
Referenced by Exit(), Init(), UpdatePlaying(), and UpdateStartMenu().
sf::Music SceneSP::music2 private
Definition at line 244 of file SceneSP.h.
Referenced by Exit(), and Init().
vector<CItem*> SceneSP::myCheckList private
Definition at line 232 of file SceneSP.h.
Referenced by checkWinLose(), RenderUI(), resetGame(), UpdatePaying(), and UpdateStartMenu().
vector<CContainer*> SceneSP::myContainerList private
Definition at line 229 of file SceneSP.h.
Referenced by checkCollision(), initShelves(), RenderShelves(), and resetGame().
vector<CNpc*> SceneSP::myNPCList private
Definition at line 233 of file SceneSP.h.
Referenced by checkCollision(), initCharacter(), RenderCharacters(), RenderTug(), resetGame(), UpdateAITimer(), UpdateBuildingGuy(), UpdateChattingman(), UpdateCustomer(), UpdateDoor(), UpdateDrunkman(), UpdateDrunkmanguy(), UpdateEasterEggGuy(), UpdateGhostman(), UpdateLegAnimation(), UpdateLogisticman(), UpdateLookingman(), UpdateShoppers(), UpdateTugofwarguy(), UpdateWalkingman(), UpdateWalkingmanoutsideX(), and UpdateWalkingmanoutsideZ().
vector<CItem*> SceneSP::myStockList private
Definition at line 230 of file SceneSP.h.
Referenced by checkPickUpItem(), DefineItem(), RenderItem(), and resetGame().
vector<CItem*> SceneSP::myTreasureList private
Definition at line 231 of file SceneSP.h.
Referenced by initShelves(), resetGame(), and UpdateStartMenu().
MS SceneSP::projectionStack
Definition at line 262 of file SceneSP.h.
Referenced by Init(), RenderMesh(), RenderText(), RenderTextOnScreen(), RenderTGAInventory(), and RenderTGAUI().
CItem* SceneSP::ptrClass private
Definition at line 223 of file SceneSP.h.
Referenced by Exit(), and initShelves().
CContainer* SceneSP::ptrContainer private
Definition at line 228 of file SceneSP.h.
Referenced by Exit(), and initShelves().
CItem* SceneSP::ptrInvSelect private
Definition at line 224 of file SceneSP.h.
Referenced by checkPickUpItem(), checkReturnPoint(), Init(), RenderHand(), UpdatePaying(), and UpdatePlayerSelection().
CItem* SceneSP::ptrItem private
Definition at line 222 of file SceneSP.h.
Referenced by DefineItem(), Exit(), and Init().
CNpc* SceneSP::ptrNPC private
Definition at line 225 of file SceneSP.h.
Referenced by Exit(), and initCharacter().
CPlayer* SceneSP::ptrplayer private
Definition at line 221 of file SceneSP.h.
Referenced by addToInventory(), checkPickUpItem(), checkReturnPoint(), checkWinLose(), Exit(), Init(), initCharacter(), RenderEasteregg(), RenderInventory(), RenderUI(), UpdateATM(), UpdateEasteregg(), UpdatePaying(), UpdatePlayerSelection(), UpdateStartMenu(), and UpdateUI().
string SceneSP::s_atm_balance private
Definition at line 220 of file SceneSP.h.
Referenced by RenderATM(), and UpdateATM().
string SceneSP::s_camera_target private
Definition at line 215 of file SceneSP.h.
Referenced by UpdateUI().
string SceneSP::s_easter_count private
Definition at line 219 of file SceneSP.h.
Referenced by RenderEasteregg(), and UpdateEasteregg().
string SceneSP::s_easter_counter private
Definition at line 218 of file SceneSP.h.
Referenced by RenderEasteregg(), and UpdateEasteregg().
string SceneSP::s_fps private
Definition at line 214 of file SceneSP.h.
Referenced by RenderUI(), and UpdateUI().
string SceneSP::s_item_name private
Definition at line 216 of file SceneSP.h.
Referenced by checkPickUpItem(), and RenderUI().
string SceneSP::s_item_price private
Definition at line 217 of file SceneSP.h.
Referenced by RenderUI(), and UpdateUI().
string SceneSP::s_money private
Definition at line 212 of file SceneSP.h.
Referenced by RenderUI(), and UpdateUI().
string SceneSP::s_position private
Definition at line 213 of file SceneSP.h.
Referenced by UpdateUI().
int SceneSP::selectionPointing private
Definition at line 226 of file SceneSP.h.
Referenced by Init(), RenderMainMenu(), RenderPauseMenu(), RenderSubMenu(), UpdateInstructionMenu(), UpdateMainMenu(), UpdatePauseMenu(), UpdatePlaying(), UpdateStartMenu(), and UpdateWinLoseMenu().
CContainer SceneSP::shelfSardineCan private
Definition at line 155 of file SceneSP.h.
bool SceneSP::showTuginstruction private
Definition at line 202 of file SceneSP.h.
Referenced by Init(), RenderTugofwarUI(), and UpdateTugofwar().
sf::Music SceneSP::sound private
Definition at line 245 of file SceneSP.h.
Referenced by Exit(), UpdateDoor(), UpdateElevator(), and UpdateSamples().
double SceneSP::timer
Definition at line 250 of file SceneSP.h.
bool SceneSP::toggleDoorBack private
Definition at line 158 of file SceneSP.h.
Referenced by Init(), and UpdateDoor().
bool SceneSP::toggleDoorFront private
Definition at line 157 of file SceneSP.h.
Referenced by Init(), and UpdateDoor().
bool SceneSP::toggleLight private
Definition at line 156 of file SceneSP.h.
Referenced by Init(), RenderATM(), RenderBeerstand(), RenderBuilding(), RenderCage(), RenderCashierTables(), RenderCharacter(), RenderDoors(), RenderElevator(), RenderFence(), RenderFerrisWheel(), RenderHand(), RenderIceBox(), RenderItem(), RenderMeatShelf(), RenderMiscEastereggs(), RenderOffice(), RenderReturnPoint(), RenderSamples(), RenderSamplestand(), RenderShelves(), RenderStorage(), RenderSupermarket(), RenderTroll(), RenderTrolleys(), RenderTug(), and UpdatePlaying().
float SceneSP::trolleyrotation private
Definition at line 171 of file SceneSP.h.
Referenced by Init(), and RenderTrolleys().
MS SceneSP::viewStack
Definition at line 262 of file SceneSP.h.
Referenced by Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), RenderTGAInventory(), and RenderTGAUI().
bool SceneSP::win private
Definition at line 200 of file SceneSP.h.
Referenced by Init(), RenderTugofwarUI(), and UpdateTugofwar().
bool SceneSP::winEaster private
Definition at line 191 of file SceneSP.h.
Referenced by checkWinLose(), Init(), RenderEasteregg(), and UpdateEasteregg().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneSP.h
MyGraphics/Source/SceneSP.cpp