My Application: CCharacter Class Reference
CCharacter Class Reference
Defines the character class.
#include <Character.h>
Public Member Functions
CCharacter (void)
Default character constructor.
CCharacter (float posX, float posY, float posZ, int state, int job)
Overloaded character constructor.
~CCharacter (void)
Default destructor.
int getCharacterState ()
Accessor function for character state.
int getAnimationType ()
Accessor function for character animation type.
float getXpos ()
Accessor function for character x position.
float getYpos ()
Accessor function for character Y position.
float getZpos ()
Accessor function for character Z position.
int getCharacterJob ()
Accessor function for character job.
void setCharacterJob (int jobNum)
Mutator function to set character job.
void setCharacterState (int state)
Mutator function to set character state.
void setAnimationType (int type)
Mutator function to set character animation type.
void setXpos (float posX)
Mutator function to set x pos of character.
void setYpos (float posY)
Mutator function to set y pos of character.
void setZpos (float posZ)
Mutator function to set z pos of character.
Private Attributes
float x
float y
float z
unsigned int characterState
unsigned int characterJob
unsigned int animationType
Detailed Description
Defines the character class.
Class Character:
Definition at line 14 of file Character.h.
Constructor & Destructor Documentation
CCharacter::CCharacter (void)
Default character constructor.
Definition at line 8 of file Character.cpp.
CCharacter::CCharacter (float posX, float posY, float posZ, int state, int job)
Overloaded character constructor.
Parameters
posX - X position of character
posY - Y position of character
posZ - Z position of character
state - character state
job - character job
Definition at line 24 of file Character.cpp.
References characterJob, characterState, x, y, and z.
CCharacter::~CCharacter (void)
Default destructor.
Definition at line 38 of file Character.cpp.
Member Function Documentation
int CCharacter::getAnimationType ()
Accessor function for character animation type.
Returns
character animation type
Definition at line 73 of file Character.cpp.
References animationType.
int CCharacter::getCharacterJob ()
Accessor function for character job.
Returns
character job
Definition at line 49 of file Character.cpp.
References characterJob.
Referenced by SceneSP::checkWinLose(), SceneSP::RenderEasteregg(), SceneSP::RenderUI(), and SceneSP::UpdateEasteregg().
int CCharacter::getCharacterState ()
Accessor function for character state.
Returns
character state
Definition at line 61 of file Character.cpp.
References characterState.
float CCharacter::getXpos ()
Accessor function for character x position.
Returns
x position of the character
Definition at line 85 of file Character.cpp.
References x.
Referenced by SceneSP::RenderCharacter().
float CCharacter::getYpos ()
Accessor function for character Y position.
Returns
Y position of the character
Definition at line 97 of file Character.cpp.
References y.
Referenced by SceneSP::RenderCharacter().
float CCharacter::getZpos ()
Accessor function for character Z position.
Returns
Z position of the character
Definition at line 109 of file Character.cpp.
References z.
Referenced by SceneSP::RenderCharacter().
void CCharacter::setAnimationType (int type)
Mutator function to set character animation type.
Parameters
type - character animation type
Definition at line 181 of file Character.cpp.
References animationType.
Referenced by CNpc::CNpc().
void CCharacter::setCharacterJob (int jobNum)
Mutator function to set character job.
Parameters
jobNum - character job
Definition at line 169 of file Character.cpp.
References characterJob.
Referenced by CNpc::CNpc(), and SceneSP::UpdateStartMenu().
void CCharacter::setCharacterState (int state)
Mutator function to set character state.
Parameters
state - character state
Definition at line 157 of file Character.cpp.
References characterState.
Referenced by CNpc::CNpc(), and CPlayer::CPlayer().
void CCharacter::setXpos (float posX)
Mutator function to set x pos of character.
Parameters
posX - X position of character
Definition at line 121 of file Character.cpp.
References x.
Referenced by CNpc::CNpc().
void CCharacter::setYpos (float posY)
Mutator function to set y pos of character.
Parameters
posY - Y position of character
Definition at line 133 of file Character.cpp.
References y.
Referenced by CNpc::CNpc().
void CCharacter::setZpos (float posZ)
Mutator function to set z pos of character.
Parameters
posZ - Z position of character
Definition at line 145 of file Character.cpp.
References z.
Referenced by CNpc::CNpc().
Field Documentation
unsigned int CCharacter::animationType private
Definition at line 41 of file Character.h.
Referenced by getAnimationType(), and setAnimationType().
unsigned int CCharacter::characterJob private
Definition at line 40 of file Character.h.
Referenced by CCharacter(), getCharacterJob(), and setCharacterJob().
unsigned int CCharacter::characterState private
Definition at line 39 of file Character.h.
Referenced by CCharacter(), getCharacterState(), and setCharacterState().
float CCharacter::x private
Definition at line 36 of file Character.h.
Referenced by CCharacter(), getXpos(), and setXpos().
float CCharacter::y private
Definition at line 37 of file Character.h.
Referenced by CCharacter(), getYpos(), and setYpos().
float CCharacter::z private
Definition at line 38 of file Character.h.
Referenced by CCharacter(), getZpos(), and setZpos().
The documentation for this class was generated from the following files:
MyGraphics/Source/Character.h
MyGraphics/Source/Character.cpp