My Application: sf::Music Class Reference
sf::Music Class Reference
Audio module
Streamed music played from an audio file.
#include <Music.hpp>
Public Member Functions
Music ()
Default constructor.
~Music ()
Destructor.
bool openFromFile (const std::string &filename)
Open a music from an audio file.
bool openFromMemory (const void *data, std::size_t sizeInBytes)
Open a music from an audio file in memory.
bool openFromStream (InputStream &stream)
Open a music from an audio file in a custom stream.
Time getDuration () const
Get the total duration of the music.
Public Member Functions inherited from sf::SoundStream
virtual ~SoundStream ()
Destructor.
void play ()
Start or resume playing the audio stream.
void pause ()
Pause the audio stream.
void stop ()
Stop playing the audio stream.
unsigned int getChannelCount () const
Return the number of channels of the stream.
unsigned int getSampleRate () const
Get the stream sample rate of the stream.
Status getStatus () const
Get the current status of the stream (stopped, paused, playing)
void setPlayingOffset (Time timeOffset)
Change the current playing position of the stream.
Time getPlayingOffset () const
Get the current playing position of the stream.
void setLoop (bool loop)
Set whether or not the stream should loop after reaching the end.
bool getLoop () const
Tell whether or not the stream is in loop mode.
Public Member Functions inherited from sf::SoundSource
SoundSource (const SoundSource &copy)
Copy constructor.
virtual ~SoundSource ()
Destructor.
void setPitch (float pitch)
Set the pitch of the sound.
void setVolume (float volume)
Set the volume of the sound.
void setPosition (float x, float y, float z)
Set the 3D position of the sound in the audio scene.
void setPosition (const Vector3f &position)
Set the 3D position of the sound in the audio scene.
void setRelativeToListener (bool relative)
Make the sound's position relative to the listener or absolute.
void setMinDistance (float distance)
Set the minimum distance of the sound.
void setAttenuation (float attenuation)
Set the attenuation factor of the sound.
float getPitch () const
Get the pitch of the sound.
float getVolume () const
Get the volume of the sound.
Vector3f getPosition () const
Get the 3D position of the sound in the audio scene.
bool isRelativeToListener () const
Tell whether the sound's position is relative to the listener or is absolute.
float getMinDistance () const
Get the minimum distance of the sound.
float getAttenuation () const
Get the attenuation factor of the sound.
Protected Member Functions
virtual bool onGetData (Chunk &data)
Request a new chunk of audio samples from the stream source.
virtual void onSeek (Time timeOffset)
Change the current playing position in the stream source.
Protected Member Functions inherited from sf::SoundStream
SoundStream ()
Default constructor.
void initialize (unsigned int channelCount, unsigned int sampleRate)
Define the audio stream parameters.
Protected Member Functions inherited from sf::SoundSource
SoundSource ()
Default constructor.
Status getStatus () const
Get the current status of the sound (stopped, paused, playing)
Private Member Functions
void initialize ()
Initialize the internal state after loading a new music.
Private Attributes
priv::SoundFile * m_file
Sound file.
Time m_duration
Music duration.
std::vector< Int16 > m_samples
Temporary buffer of samples.
Mutex m_mutex
Mutex protecting the data.
Additional Inherited Members
Public Types inherited from sf::SoundSource
enum Status { Stopped, Paused, Playing }
Enumeration of the sound source states.
Protected Attributes inherited from sf::SoundSource
unsigned int m_source
OpenAL source identifier.
Detailed Description
Streamed music played from an audio file.
Music objects are sounds that are streamed rather than completely loaded in memory.
This is especially useful for compressed music that usually takes hundreds of MB when it is uncompressed: by streaming it instead of loading it entirely, you avoid saturating the memory and have almost no loading delay.
Apart from that, sf::Music has almost the same features as the sf::SoundBuffer / sf::Sound pair: you can play/pause/stop it, request its parameters (channels, sample rate), change the way it is played (pitch, volume, 3D position, ...), etc.
As a sound stream, a music is played in its own thread in order not to block the rest of the program. This means that you can leave the music alone after calling play(), it will manage itself very well.
Usage example:
// Declare a new music
sf::Music music;
// Open it from an audio file
if (!music.openFromFile("music.ogg"))
{
    // error...
}
// Change some parameters
music.setPosition(0, 1, 10); // change its 3D position
music.setPitch(2);           // increase the pitch
music.setVolume(50);         // reduce the volume
music.setLoop(true);         // make it loop
// Play it
music.play();
See also
sf::Sound, sf::SoundStream
Definition at line 52 of file Music.hpp.
Constructor & Destructor Documentation
sf::Music::Music ()
Default constructor.
sf::Music::~Music ()
Destructor.
Member Function Documentation
Time sf::Music::getDuration () const
Get the total duration of the music.
Returns
Music duration
void sf::Music::initialize () private
Initialize the internal state after loading a new music.
virtual bool sf::Music::onGetData (Chunk & data) protected virtual
Request a new chunk of audio samples from the stream source.
This function fills the chunk from the next samples to read from the audio file.
Parameters
data Chunk of data to fill
Returns
True to continue playback, false to stop
Implements sf::SoundStream.
virtual void sf::Music::onSeek (Time timeOffset) protected virtual
Change the current playing position in the stream source.
Parameters
timeOffset New playing position, from the beginning of the music
Implements sf::SoundStream.
bool sf::Music::openFromFile (const std::string & filename)
Open a music from an audio file.
This function doesn't start playing the music (call play() to do so). Here is a complete list of all the supported audio formats: ogg, wav, flac, aiff, au, raw, paf, svx, nist, voc, ircam, w64, mat4, mat5 pvf, htk, sds, avr, sd2, caf, wve, mpc2k, rf64.
Parameters
filename Path of the music file to open
Returns
True if loading succeeded, false if it failed
See also
openFromMemory, openFromStream
Referenced by SceneSP::Init(), SceneSP::UpdateCage(), SceneSP::UpdateDoor(), SceneSP::UpdateElevator(), SceneSP::UpdateGaben(), SceneSP::UpdateMiscEasteregg(), SceneSP::UpdatePlaying(), SceneSP::UpdateSamples(), and SceneSP::UpdateTroll().
bool sf::Music::openFromMemory (const void * data, std::size_t sizeInBytes)
Open a music from an audio file in memory.
This function doesn't start playing the music (call play() to do so). Here is a complete list of all the supported audio formats: ogg, wav, flac, aiff, au, raw, paf, svx, nist, voc, ircam, w64, mat4, mat5 pvf, htk, sds, avr, sd2, caf, wve, mpc2k, rf64. Since the music is not loaded completely but rather streamed continuously, the data must remain available as long as the music is playing (i.e. you can't deallocate it right after calling this function).
Parameters
data Pointer to the file data in memory
sizeInBytes Size of the data to load, in bytes
Returns
True if loading succeeded, false if it failed
See also
openFromFile, openFromStream
bool sf::Music::openFromStream (InputStream & stream)
Open a music from an audio file in a custom stream.
This function doesn't start playing the music (call play() to do so). Here is a complete list of all the supported audio formats: ogg, wav, flac, aiff, au, raw, paf, svx, nist, voc, ircam, w64, mat4, mat5 pvf, htk, sds, avr, sd2, caf, wve, mpc2k, rf64. Since the music is not loaded completely but rather streamed continuously, the stream must remain alive as long as the music is playing (i.e. you can't destroy it right after calling this function).
Parameters
stream Source stream to read from
Returns
True if loading succeeded, false if it failed
See also
openFromFile, openFromMemory
Field Documentation
Time sf::Music::m_duration private
Music duration.
Definition at line 174 of file Music.hpp.
priv::SoundFile* sf::Music::m_file private
Sound file.
Definition at line 173 of file Music.hpp.
Mutex sf::Music::m_mutex private
Mutex protecting the data.
Definition at line 176 of file Music.hpp.
std::vector<Int16> sf::Music::m_samples private
Temporary buffer of samples.
Definition at line 175 of file Music.hpp.
The documentation for this class was generated from the following file:
SFML/include/SFML/Audio/Music.hpp