My Application: CPlayer Class Reference
CPlayer Class Reference
Player class which stores the player's money and inventory.
#include <Player.h>
Public Member Functions
CPlayer (void)
Default player constructor.
CPlayer (float setMoney, int setItemsHeld, int setMaxItemCapacity)
Overloaded player constructor.
~CPlayer (void)
Default destructor.
float getMoney ()
Accessor function for the amount of money the player has.
int getMaxItemCapacity ()
Accessor function for the max amount of items the player can have.
int getItemHeld ()
Accessor function for the number of items the player is holding.
std::vector< CItem * > getVector ()
void setInventory (CItem *pickedUp)
Mutator function to add an item picked up by the player.
void setInventory (CItem *pickedUp, int slot)
Mutator function to add an item picked up by the player to a specific inventory slot.
void setInventory (CItem pickedUp, int slot)
void setMoney (float newMoney)
Mutator function to set the players current money.
CItem * getItem (int i)
Accessor function for the items held by the player.
Public Member Functions inherited from CCharacter
CCharacter (void)
Default character constructor.
CCharacter (float posX, float posY, float posZ, int state, int job)
Overloaded character constructor.
~CCharacter (void)
Default destructor.
int getCharacterState ()
Accessor function for character state.
int getAnimationType ()
Accessor function for character animation type.
float getXpos ()
Accessor function for character x position.
float getYpos ()
Accessor function for character Y position.
float getZpos ()
Accessor function for character Z position.
int getCharacterJob ()
Accessor function for character job.
void setCharacterJob (int jobNum)
Mutator function to set character job.
void setCharacterState (int state)
Mutator function to set character state.
void setAnimationType (int type)
Mutator function to set character animation type.
void setXpos (float posX)
Mutator function to set x pos of character.
void setYpos (float posY)
Mutator function to set y pos of character.
void setZpos (float posZ)
Mutator function to set z pos of character.
Private Attributes
int itemsHeld
int maxItemCapacity
float money
std::vector< CItem * > myInventoryList
Detailed Description
Player class which stores the player's money and inventory.
Class Item:
Definition at line 9 of file Player.h.
Constructor & Destructor Documentation
CPlayer::CPlayer (void)
Default player constructor.
Definition at line 9 of file Player.cpp.
References IDLE, itemsHeld, maxItemCapacity, money, and CCharacter::setCharacterState().
CPlayer::CPlayer (float setMoney, int setItemsHeld, int setMaxItemCapacity)
Overloaded player constructor.
Parameters
setMoney - sets the players money
setItemsHeld - sets the number of items held by the players
setMaxItemCapacity - sets the max item capacity of the player
Definition at line 26 of file Player.cpp.
References IDLE, itemsHeld, maxItemCapacity, money, CCharacter::setCharacterState(), and setMoney().
CPlayer::~CPlayer (void)
Default destructor.
Definition at line 40 of file Player.cpp.
Member Function Documentation
CItem * CPlayer::getItem (int i)
Accessor function for the items held by the player.
Returns
item held
Definition at line 51 of file Player.cpp.
References myInventoryList.
Referenced by SceneSP::checkPickUpItem(), SceneSP::checkReturnPoint(), SceneSP::Init(), SceneSP::RenderUI(), SceneSP::UpdatePaying(), SceneSP::UpdatePlayerSelection(), and SceneSP::UpdateUI().
int CPlayer::getItemHeld ()
Accessor function for the number of items the player is holding.
Returns
number of items held
Definition at line 75 of file Player.cpp.
References myInventoryList.
Referenced by SceneSP::RenderInventory(), and SceneSP::UpdatePlayerSelection().
int CPlayer::getMaxItemCapacity ()
Accessor function for the max amount of items the player can have.
Returns
max item capacity
Definition at line 87 of file Player.cpp.
References maxItemCapacity.
Referenced by SceneSP::Init().
float CPlayer::getMoney ()
Accessor function for the amount of money the player has.
Returns
player's money
Definition at line 63 of file Player.cpp.
References money.
Referenced by SceneSP::UpdateATM(), SceneSP::UpdatePaying(), and SceneSP::UpdateUI().
std::vector< CItem * > CPlayer::getVector ()
Definition at line 117 of file Player.cpp.
References myInventoryList.
Referenced by SceneSP::checkWinLose(), SceneSP::RenderInventory(), and SceneSP::UpdatePaying().
void CPlayer::setInventory (CItem * pickedUp)
Mutator function to add an item picked up by the player.
Parameters
pickedUp - adds the item picked up
Definition at line 99 of file Player.cpp.
References myInventoryList.
Referenced by SceneSP::addToInventory(), SceneSP::checkReturnPoint(), SceneSP::Init(), and SceneSP::UpdatePaying().
void CPlayer::setInventory (CItem * pickedUp, int slot)
Mutator function to add an item picked up by the player to a specific inventory slot.
Parameters
pickedUp - adds the item picked up
slot - the inventory slot to add the item to
Definition at line 112 of file Player.cpp.
References myInventoryList.
void CPlayer::setInventory (CItem pickedUp, int slot)
void CPlayer::setMoney (float newMoney)
Mutator function to set the players current money.
Parameters
newMoney - the players new amount of money
Definition at line 129 of file Player.cpp.
References money.
Referenced by CPlayer(), SceneSP::UpdateATM(), and SceneSP::UpdatePaying().
Field Documentation
int CPlayer::itemsHeld private
Definition at line 13 of file Player.h.
Referenced by CPlayer().
int CPlayer::maxItemCapacity private
Definition at line 14 of file Player.h.
Referenced by CPlayer(), and getMaxItemCapacity().
float CPlayer::money private
Definition at line 15 of file Player.h.
Referenced by CPlayer(), getMoney(), and setMoney().
std::vector<CItem*> CPlayer::myInventoryList private
Definition at line 16 of file Player.h.
Referenced by getItem(), getItemHeld(), getVector(), and setInventory().
The documentation for this class was generated from the following files:
MyGraphics/Source/Player.h
MyGraphics/Source/Player.cpp