My Application: MyGraphics/Source/MeshBuilder.cpp File Reference
MeshBuilder.cpp File Reference
#include "MeshBuilder.h"
#include <GL\glew.h>
#include <vector>
#include "Vertex.h"
#include "MyMath.h"
#include "LoadOBJ.h"
Functions
float sphereX (float phi, float theta)
float sphereY (float phi, float theta)
float sphereZ (float phi, float theta)
float cylinderX (float theta)
float cylinderZ (float theta)
Function Documentation
float cylinderX (float theta)
Definition at line 488 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float cylinderZ (float theta)
Definition at line 493 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float sphereX (float phi, float theta)
Definition at line 409 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().
float sphereY (float phi, float theta)
Definition at line 412 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().
float sphereZ (float phi, float theta)
Definition at line 415 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().