#ifndef _DEFINE_ENUM_H
#define _DEFINE_ENUM_H

enum GEOMETRY_TYPE
	{
		GEO_AXES,
		GEO_TEXT,	
		GEO_FRONT,
		GEO_BOTTOM,
		GEO_BACK,
		GEO_TOP,
		GEO_LEFT,
		GEO_RIGHT,
		GEO_SUPERMARKET,
		GEO_TROLLEY,
		GEO_SHELF,
		GEO_CASHIER,
		GEO_DOOR,
		GEO_ICEBOX,
		GEO_SAMPLESTAND,
		GEO_CAN_SARDINE,
		GEO_CAN_PEAS,
		GEO_CAN_BROWN,
		GEO_CAN_TOMATO,
		GEO_CAN_BEANS,
		GEO_CAN_MELON,
		GEO_CAN_VARGA,
		//========New Can===========
		GEO_CAN_BRAN,
		GEO_CAN_SODA,
		GEO_CAN_GLUWATER,
		GEO_CAN_ROOTBEERFLOATS,
		GEO_CAN_MTNDEW,
		GEO_CAN_SODAFEST,
		GEO_CAN_REDMONSTER,
		GEO_CAN_HUMANS,
		GEO_CEREAL_1,
		GEO_CEREAL_2,
		GEO_CEREAL_3,
		GEO_CEREAL_4,
		GEO_CEREAL_5,
		GEO_EASTEREGG_1,
		GEO_EASTEREGG_2,
		GEO_EASTEREGG_3,

		GEO_FENCE,
		GEO_UI_SCREEN,
		NUM_GEOMETRY,
	};
enum ROW_TYPE
{
	ROW_TOP,
	ROW_MIDDLE,
	ROW_BOTTOM,
	NUM_ROW,
};
enum UNIFORM_TYPE
{
	U_MVP = 0,
	U_MODELVIEW,
	U_MODELVIEW_INVERSE_TRANSPOSE,
	U_MATERIAL_AMBIENT,
	U_MATERIAL_DIFFUSE,
	U_MATERIAL_SPECULAR,
	U_MATERIAL_SHININESS,
	U_LIGHT0_POSITION,
	U_LIGHT0_TYPE,
	U_LIGHT0_COLOR,
	U_LIGHT0_POWER,
	U_LIGHT0_KC,
	U_LIGHT0_KL,
	U_LIGHT0_KQ,
	U_LIGHTENABLED,
	U_LIGHT0_SPOTDIRECTION,
	U_LIGHT0_COSCUTOFF,
	U_LIGHT0_COSINNER,
	U_LIGHT0_EXPONENT,

	U_LIGHT1_POSITION,
	U_LIGHT1_TYPE,
	U_LIGHT1_COLOR,
	U_LIGHT1_POWER,
	U_LIGHT1_KC,
	U_LIGHT1_KL,
	U_LIGHT1_KQ,
	U_LIGHT1_SPOTDIRECTION,
	U_LIGHT1_COSCUTOFF,
	U_LIGHT1_COSINNER,
	U_LIGHT1_EXPONENT,

	U_NUMLIGHTS,
	//add these enum in UNIFORM_TYPE before U_TOTAL
	U_COLOR_TEXTURE_ENABLED,
	U_COLOR_TEXTURE,
	U_TEXT_ENABLED,
	U_TEXT_COLOR,

	U_TOTAL,
};
enum CHARACTER_JOB
{
	CASHIER,
	CUSTOMER,
	PART_TIME_WORKER,
	NUM_JOB,
};
enum CHARACTER_STATE
{
	IDLE,
	WALKING,
	RUNNING,

	NUM_STATE,
};


#endif